import {esc,btn} from './ui.js';
import {companyOf,productOf} from './model.js';
const ruleBtn=(label,a,attrs='',tone='ghost')=>btn(label,'care-rule-'+a,attrs,tone);
export function careRulesPage(s){const cs=s.care;initCareRules(cs);const r=cs.rules.find(x=>x.id===cs.ruleEditor.id);const rows=cs.rules.map(x=>`<tr><td>${ruleBtn(esc(x.name),'select',`data-id="${x.id}"`,'text')}<small>v${x.version}</small></td><td>${esc(productOf(s,x.product).name)}</td><td class="care-rule-description">${esc(x.spec)}</td><td><span class="care-status">${x.enabled?'已啟用':'已停用'}</span></td><td>${ruleBtn('查看詳情','select',`data-id="${x.id}"`,'small ghost')}</td></tr>`).join('');
const list=`<section class="dash-panel"><header><div><h2>目前規則清單</h2><p>${cs.rules.length} 份規則 · ${cs.rules.filter(x=>x.enabled).length} 份已啟用。點選規則查看原始輸入與 AI 判斷規範。</p></div>${ruleBtn('新增規則','new','','primary')}</header><div class="table-scroll"><table class="dash-table care-rule-table"><thead><tr><th>規則名稱／版本</th><th>適用產品</th><th>規則的 AI 判斷描述</th><th>狀態</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
if(!cs.ruleModal)return list;
const readOnly=r?`<div class="care-section"><h3>規則資料</h3><p>${esc(productOf(s,r.product).name)} · v${r.version} · ${r.enabled?'已啟用':'已停用'}</p></div><div class="care-section"><h3>當初人員手動輸入的內容</h3><div class="care-rule-original">${esc(r.description)}</div></div><div class="care-section"><h3>AI 判讀內容／已確認的判斷規範</h3><div class="care-ai care-rule-original">${esc(r.spec)}</div><p class="care-muted">目前為模擬 AI 規範；此版本用於後續判斷，修改需重新確認與試跑。</p></div><div class="care-section care-inline">${ruleBtn('刪除規則','delete',`data-id="${r.id}"`,'care-rule-danger')}${ruleBtn('關閉','close')}</div>`:'';
return list.replace('<section class="dash-panel">','<section class="dash-panel" inert>')+`<div class="care-rule-overlay"><section class="care-rule-dialog" role="dialog" aria-modal="true" aria-labelledby="care-rule-title" tabindex="-1"><header class="care-rule-dialog-header"><div><h2 id="care-rule-title">${cs.ruleModal==='new'?'新增規則':cs.ruleModal==='edit'?'修改規則':esc(r.name)}${r?`<button class="care-rule-switch ${r.enabled?'is-on':''}" data-action="care-rule-toggle" data-id="${r.id}" role="switch" aria-checked="${r.enabled}" aria-label="啟用${esc(r.name)}"><span class="care-switch-track"><i></i></span><small>${r.enabled?'已啟用':'已停用'}</small></button>`:''}</h2><p>${cs.ruleModal==='detail'?'查看原始描述與 AI 判讀內容':'描述需求 → 確認 AI 規範 → 試跑 → 保存'}</p></div><div class="care-rule-header-actions">${cs.ruleModal==='detail'?ruleBtn('修改規則','edit','','primary'):''}${ruleBtn('關閉','close','aria-label="關閉規則彈窗"')}</div></header>${cs.notice?`<div class="care-notice" role="status">${esc(cs.notice)}</div>`:''}<div class="care-rule-dialog-body">${cs.ruleModal==='detail'?readOnly:careRuleEditor(s)}</div></section></div>`;}
const ruleExamples={low:'針對 E2B 使用權有效的公司，如果最近兩週沒有使用生成或分析功能，就提醒負責人了解是否遇到操作障礙。有客服案件正在處理，或最近一個月已經關懷過的公司先不要重複聯繫。',drop:'找出最近兩週文案生成明顯少於前兩週、但仍有使用其他功能的 E2B 公司。先了解工作流程是否改變，不直接認定客戶流失；沒有前期資料就交由人員確認。',high:'如果 E2B 客戶最近一個月持續頻繁使用文案功能，但還沒使用商品圖片生成，可以提醒負責人評估是否適合提供圖片功能教學。不要推荐正在維護或尚未開放的功能。',web:'官網客戶如果長時間沒有更新網站，先看是否有實際更新需求。若客服正在跟進發布問題，先不要重複寄關懷信；缺少網站更新資料時標示資料不足。'};
export function initCareRules(cs){if(cs.ruleEditor)return;cs.rules=cs.rules.map(r=>({id:r.id,name:r.name,product:r.product,enabled:r.enabled,description:ruleExamples[r.id],spec:ruleExamples[r.id]+'\n\n判斷時請引用資料期間與事實，區分符合、不符合、資料不足。只提出關懷建議，Mail 必須由人員確認。',version:1}));cs.ruleEditor={id:'low',name:cs.rules[0].name,product:'e2b',description:cs.rules[0].description,spec:cs.rules[0].spec,parsed:true,confirmed:false,trial:null};}
function loadCareRule(cs,id){const r=cs.rules.find(x=>x.id===id);cs.ruleEditor={id:r.id,name:r.name,product:r.product,description:r.description,spec:r.spec,parsed:true,confirmed:false,trial:null};}
function careRuleEditor(s){const cs=s.care;initCareRules(cs);const e=cs.ruleEditor,r=cs.rules.find(x=>x.id===e.id);
return `<section class="dash-panel care-detail"><header><div><h2>${r?'編輯規則':'新增規則'}</h2><p>${r?`目前正式版本 v${r.version}；修改內容先存為待確認草稿。`:'不需要選擇計量單位或固定判斷指標。'}</p></div></header><div class="care-section"><h3>1. 用你的話描述需求</h3><label>規則名稱<input data-care-editor="name" value="${esc(e.name)}" placeholder="例如：需要入門協助的客戶"></label><label>適用產品<select data-care-editor="product">${s.products.map(p=>`<option value="${p.id}" ${p.id===e.product?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>希望 AI 如何判斷？<textarea rows="6" data-care-editor="description" placeholder="描述對象、值得關注的情況、例外與希望的後續行動。例如：新客戶開通後還沒有開始使用，請先了解是否需要入門教學。">${esc(e.description)}</textarea></label><p class="care-muted">可描述頻率、變化、功能使用、客服狀況與聯繫限制。新增規則不需要工程師新增欄位。</p>${ruleBtn('AI 解析並整理規範','parse','','primary')} ${ruleBtn('帶入高頻使用範例','example')}</div><div class="care-section"><h3>2. 確認 AI 理解的規範</h3>${e.parsed?`<div class="care-ai"><b>解析展示</b><p>本機未連接 AI，以下將原文整理成規範草稿供你修改，並未完成語意理解或驗證。</p><p>需要確認：哪些資料足以判斷？「頻繁／明顯／長時間」如何定義？資料缺漏時應如何處理？AI 不應自行補上數字門檻。</p></div><label>可編輯的判斷規範<textarea rows="9" data-care-editor="spec">${esc(e.spec)}</textarea></label><label class="care-check"><input type="checkbox" data-care-editor="confirmed" ${e.confirmed?'checked':''}>我已確認規範忠實表達需求，作為此版本的 AI 判斷依據。</label><p class="care-muted">修改原始描述需重新解析；修改規範需重新確認並試跑。</p>`:'<p class="care-muted">先描述規則，再讓 AI 整理。未確認的規範不會啟用。</p>'}</div><div class="care-section"><h3>3. 試跑並查看逐公司判斷</h3>${ruleBtn('試跑這份規範','trial',`${!e.parsed||!e.confirmed?'disabled':''}`,'primary')}<p class="care-muted">既有範例顯示固定測試結果；自訂或修改規範因尚未連接 AI，顯示「待 AI 判斷」，不會套用舊門檻。</p>${e.trial?`<div class="care-trial">${e.trial.map(x=>`<article><b>${esc(companyOf(s,x.company).short)} <span class="care-status">${x.result}</span></b><p>${esc(x.evidence)}</p><small>${esc(x.reason)}</small></article>`).join('')}</div>`:''}</div><div class="care-section"><h3>4. 保存與啟用</h3>${ruleBtn('保存並啟用此版本','publish',`${!e.confirmed||!e.trial?'disabled':''}`,'primary')}<p class="care-muted">保存後由 AI 讀取規範與公司資料，回傳結論、證據與缺漏資訊。Demo 只展示啟用狀態，不執行實際 AI 判斷。已產生的關懷案件保留原版本來源。</p></div></section>`;}
export function careRuleAction(s,action,id){const cs=s.care;initCareRules(cs);const e=cs.ruleEditor;cs.notice='';
if(action==='select'){loadCareRule(cs,id);cs.ruleModal='detail';}
if(action==='delete'){const r=cs.rules.find(x=>x.id===id);if(!r)return;cs.rules=cs.rules.filter(x=>x.id!==id);cs.ruleModal=null;cs.notice=`已刪除「${r.name}」（本次展示）；既有關懷案件與紀錄保留。`;return;}
if(action==='edit')cs.ruleModal='edit';
if(action==='close'){cs.ruleModal=null;return;}
if(action==='new'){cs.ruleModal='new';cs.ruleEditor={id:'',name:'',product:'e2b',description:'',spec:'',parsed:false,confirmed:false,trial:null};}
if(action==='example'){e.name='高頻使用與功能推薦';e.product='e2b';e.description=ruleExamples.high;e.parsed=false;e.confirmed=false;e.trial=null;}
if(action==='parse'){if(!e.name.trim()||!e.description.trim()){cs.notice='請填寫規則名稱與需求描述。';return;}e.spec=`適用對象：${productOf(s,e.product).name} 的客戶公司。\n\n判斷需求：\n${e.description.trim()}\n\n判斷輸出：符合／不符合／資料不足，並列出資料期間、引用事實、理由與建議行動。\n\n資訊不足或描述有歧義時：列出待確認問題，不自行猜測門檻與客戶意圖。\n\n執行方式：建立關懷建議；信件由人員確認後寄送。`;e.parsed=true;e.confirmed=false;e.trial=null;cs.notice='已產生規範草稿（模擬整理），請修改並確認內容。';}
if(action==='trial'){if(!e.confirmed||!e.parsed)return;const r=cs.rules.find(x=>x.id===e.id),unchanged=r&&e.spec===r.spec&&e.description===r.description&&e.product===r.product&&Object.hasOwn(ruleExamples,r.id)&&r.version===1;e.trial=cs.items.filter(x=>x.product===e.product).map(x=>({company:x.company,evidence:x.evidence,result:unchanged?(x.rule===r.id?(r.id==='web'?'資料不足':'符合'):'不符合'):'待 AI 判斷',reason:unchanged?(x.rule===r.id?'固定範例：此情境符合所選規範的關注方向，仍需人工確認。':'固定範例：未列為此規範的關注對象。'):'自訂規範已接收；未接 AI，無法提供真實判斷結果。'}));cs.notice='試跑展示已完成；結果不會自動寄信。';}
if(action==='publish'){if(!e.confirmed||!e.trial||!e.name.trim()||!e.spec.trim())return;let r=cs.rules.find(x=>x.id===e.id);if(!r){r={id:'rule-'+Date.now(),version:0};cs.rules.push(r);e.id=r.id;}Object.assign(r,{name:e.name,product:e.product,description:e.description,spec:e.spec,enabled:true,version:r.version+1});e.confirmed=false;e.trial=null;cs.ruleModal=null;cs.notice=`已保存並啟用「${r.name}」v${r.version}（展示）。新增規則會由 AI 判斷，不套用程式門檻。`;}
if(action==='toggle'){const r=cs.rules.find(x=>x.id===id);r.enabled=!r.enabled;cs.notice=`「${r.name}」已${r.enabled?'啟用':'停用'}。`;}
if(action==='scan'){cs.tab='rules';cs.notice=`已載入 ${cs.rules.filter(x=>x.enabled).length} 份啟用規範（展示）。請選擇規則試跑，查看判斷依據；未接 AI，不執行實際分類。`;}
}

