import {DEMO_DATE} from './data.js';
import {companyOf,productOf,seats,serviceStatus,daysUntil} from './model.js';
import {esc,status,btn,link} from './ui.js';

const chartColors=['#2878d0','#19a893','#e6aa40','#d76a6a','#8e9cac'];
function dashPanel(title,sub,body,tools='',cls=''){return `<section class="dash-panel ${cls}"><header><div><h2>${title}</h2><p>${sub}</p></div>${tools}</header>${body}</section>`;}
function dashLegend(items){return `<div class="chart-legend">${items.map(([label,color,value])=>`<span><i style="background:${color}"></i>${label}${value!==undefined?`<b>${value}</b>`:''}</span>`).join('')}</div>`;}
function trendSvg(s,v,es){
  const n=Number(v.dashPeriod||90)===30?7:Number(v.dashPeriod||90)===180?6:7;
  const labels=Number(v.dashPeriod||90)===180?['5月','6月','7月','8月','9月','10月']:Number(v.dashPeriod||90)===30?['9/05','9/10','9/15','9/20','9/25','9/30','10/05']:['7/05','7/20','8/05','8/20','9/05','9/20','10/05'];
  const used=v.dashMetric==='usage';const ps=s.products.filter(p=>v.dashProduct==='all'||!v.dashProduct||p.id===v.dashProduct);
  const series=ps.map((p,i)=>{const end=used?s.quotas.filter(q=>q.product===p.id).reduce((a,q)=>a+q.used,0):es.filter(e=>e.product===p.id&&['使用中','即將到期'].includes(serviceStatus(s,e).label)).length;return {name:p.name,color:chartColors[s.products.indexOf(p)%2],values:Array.from({length:n},(_,j)=>j===n-1?end:Math.max(0,Math.round(end*((i===0?.28:.65)+j/(n-1)*(i===0?.72:.35))+Math.sin(j+i)*end*.08)))};});
  const max=Math.max(used?10:4,...series.flatMap(r=>r.values));const ceiling=used?Math.ceil(max/200)*200:Math.ceil(max/2)*2;
  const x=j=>52+j*(608/(n-1)),y=num=>205-num/ceiling*170;
  return dashLegend(series.map(r=>[r.name,r.color]))+`<div class="chart-container"><svg viewBox="0 0 700 250" role="img" aria-label="${used?'產品功能用量':'有效產品使用權'}趨勢，歷史點為展示資料，末點依目前資料計算">${Array.from({length:5},(_,i)=>{const val=ceiling*i/4;return `<line x1="52" x2="665" y1="${y(val)}" y2="${y(val)}" class="chart-grid"/><text x="40" y="${y(val)+4}" text-anchor="end">${val}</text>`;}).join('')}${labels.map((l,j)=>`<text x="${x(j)}" y="232" text-anchor="middle">${l}</text>`).join('')}${series.map(r=>{const pts=r.values.map((num,j)=>`${x(j)},${y(num)}`);return `<path d="M${pts.join(' L')} L${x(n-1)},205 L52,205 Z" fill="${r.color}" opacity=".06"/><polyline points="${pts.join(' ')}" fill="none" stroke="${r.color}" stroke-width="3" stroke-linejoin="round"/>${r.values.map((num,j)=>`<circle cx="${x(j)}" cy="${y(num)}" r="4" fill="white" stroke="${r.color}" stroke-width="2"><title>${r.name} · ${labels[j]} · ${num}${used?' 次':' 筆使用權'}</title></circle>`).join('')}`;}).join('')}</svg></div><div class="chart-footnote">${used?'次數按展示配額項目加總，非營收指標。':'以公司產品使用權為單位，同公司兩產品分別計算。'} 歷史曲線為展示資料。</div>`;
}
function donutSvg(es,s,product){
  const labels=['使用中','即將到期','已到期','暫停／未開通'];const values=labels.map((_,i)=>es.filter(e=>{const a=serviceStatus(s,e).label;return i===0?a==='使用中':i===1?a==='即將到期':i===2?a==='已到期':!['使用中','即將到期','已到期'].includes(a);}).length);
  const total=es.length||1,circ=2*Math.PI*70;let offset=0;
  const rings=values.map((value,i)=>{const len=value/total*circ;const r=`<circle cx="110" cy="110" r="70" fill="none" stroke="${chartColors[i]}" stroke-width="22" stroke-dasharray="${len} ${circ-len}" stroke-dashoffset="${-offset}" transform="rotate(-90 110 110)"><title>${labels[i]}：${value} 筆</title></circle>`;offset+=len;return r;});
  return `<div class="donut-layout"><svg viewBox="0 0 220 220" role="img" aria-label="使用權分布：${labels.map((l,i)=>l+values[i]).join('，')}"><circle cx="110" cy="110" r="70" fill="none" stroke="#eff2f7" stroke-width="22"/>${rings.join('')}<text x="110" y="108" text-anchor="middle" class="donut-total">${es.length}</text><text x="110" y="131" text-anchor="middle">產品使用權</text></svg><div class="distribution-list">${labels.map((label,i)=>`<button data-page="companies" data-product-filter="${product}" data-preset="${label==='暫停／未開通'?'暫停／待開通':label}"><i style="background:${chartColors[i]}"></i><span>${label}</span><b>${values[i]}</b><small>${Math.round(values[i]/total*100)}%</small></button>`).join('')}</div></div>`;
}
export function dashboard(s,v){
  const product=v.dashProduct||'all';const es=s.entitlements.filter(e=>product==='all'||e.product===product);const companyIds=new Set(es.map(e=>e.company));
  const active=es.filter(e=>['使用中','即將到期'].includes(serviceStatus(s,e).label));const due=es.filter(e=>daysUntil(e.end)>=0&&daysUntil(e.end)<=30);
  const qs=s.quotas.filter(q=>product==='all'||q.product===product);const fs=s.features.filter(f=>product==='all'||f.product===product);const maintenance=fs.filter(f=>!f.enabled||f.status==='維護中');
  const kpis=[['服務公司',companyIds.size,`${s.companies.filter(c=>companyIds.has(c.id)&&!c.enabled).length} 間暫停`,'companies','building'],['有效使用權',active.length,`共 ${es.length} 筆 · ${due.length} 筆 30 天內到期`,'companies','key'],['維護／停用功能',maintenance.length,`${fs.length} 項功能 · 全域與產品分別管理`,'products','pulse'],['高用量項目',qs.filter(q=>q.used/q.total>=.85).length,'使用比例 ≥ 85%','quotas','bar']];
  const health=s.products.filter(p=>product==='all'||p.id===product).map(p=>{const features=s.features.filter(f=>f.product===p.id);const enabled=features.filter(f=>f.enabled);const se=s.entitlements.filter(e=>e.product===p.id);const n=se.map(e=>seats(s,e));const total=n.reduce((a,b)=>a+b.limit,0),used=n.reduce((a,b)=>a+b.used,0),invites=n.reduce((a,b)=>a+b.invited,0);return `<div class="dash-product-row"><div class="dash-product-id"><span>${p.id==='e2b'?'E':'W'}</span><div>${link(p.name,'product',`data-id="${p.id}"`)}<small>${p.version} · ${status(p.enabled?p.status:'停止服務',p.enabled?'ok':'bad')}</small></div></div><div class="dash-health-bars"><div><span>功能啟用</span><div class="horizontal-track"><i style="width:${enabled.length/features.length*100}%"></i></div><b>${enabled.length}/${features.length}</b></div><div><span>帳號名額</span><div class="horizontal-track teal"><i style="width:${total?used/total*100:0}%"></i></div><b>${used}/${total}</b></div></div><small>${se.length} 間公司 · ${invites} 個邀請中</small></div>`;}).join('');
  const quotaChart=qs.slice().sort((a,b)=>b.used/b.total-a.used/a.total).slice(0,5).map(q=>{const pct=Math.round(q.used/q.total*100);return `<button class="quota-chart-row" data-action="quotaEdit" data-id="${q.id}"><div><b>${companyOf(s,q.company).short}</b><small>${q.name}</small></div><div class="horizontal-track ${pct>=100?'danger':pct>=85?'amber':'blue'}"><i style="width:${Math.min(pct,100)}%"></i></div><strong>${pct}%</strong></button>`;}).join('');
  const expiring=es.filter(e=>daysUntil(e.end)<=30).sort((a,b)=>a.end.localeCompare(b.end));
  const dueRows=expiring.slice(0,4).map(e=>`<tr><td>${link(companyOf(s,e.company).short,'company',`data-id="${e.company}" data-product="${e.product}"`)}</td><td>${productOf(s,e.product).name}</td><td class="mono">${e.end}</td><td>${status(daysUntil(e.end)<0?'已到期':daysUntil(e.end)+' 天','warn')}</td></tr>`).join('');
  const tasks=[...s.tasks.filter(t=>t.state!=='已處理'&&(product==='all'||t.product===product))].slice(0,4);
  const taskRows=tasks.map(t=>`<div class="dash-task"><span class="priority ${t.priority==='高'?'high':''}">${t.priority}</span><div><b>${esc(t.title)}</b><p>${esc(t.desc)}</p></div>${btn('處理','task',`data-id="${t.id}"`,'small ghost')}</div>`).join('');
  const releaseRows=s.releases.filter(r=>product==='all'||r.product===product).slice(0,3).map(r=>`<tr><td>${link(r.name,'release',`data-id="${r.id}"`)}</td><td>${productOf(s,r.product).name}</td><td class="mono">${r.version}</td><td>${status(r.status)}</td><td class="mono">${r.time}</td></tr>`).join('');
  return `<div class="dashboard"><div class="dashboard-context"><span><i></i>資料基準 ${DEMO_DATE} <small>／ 展示環境</small></span><div><select aria-label="Dashboard產品" data-view="dashProduct"><option value="all" ${product==='all'?'selected':''}>全部產品</option>${s.products.map(p=>`<option value="${p.id}" ${product===p.id?'selected':''}>${p.name}</option>`).join('')}</select><select aria-label="Dashboard期間" data-view="dashPeriod">${[30,90,180].map(n=>`<option value="${n}" ${Number(v.dashPeriod||90)===n?'selected':''}>近 ${n} 天</option>`).join('')}</select>${btn('重新整理','refreshDashboard','','ghost small')}</div></div><div class="dash-kpis">${kpis.map(([label,num,hint,page,icon],i)=>`<button data-page="${page}" data-product-filter="${product}" ${i===1?'data-preset="有效使用權"':''} class="dash-kpi"><div><span>${label}</span><i class="kpi-symbol s${i}">${['▥','◇','⌁','▤'][i]}</i></div><strong>${num}<small>${i===0?'間':i===1?'筆':'項'}</small></strong><p>${hint}</p></button>`).join('')}</div><div class="dash-chart-grid">${dashPanel(v.dashMetric==='usage'?'產品功能用量趨勢':'有效使用權趨勢','觀察 E2B 與官網的營運變化',trendSvg(s,v,es),`<div class="segmented">${btn('使用權','dashMetric','data-value="rights"',v.dashMetric!=='usage'?'selected small':'ghost small')}${btn('用量','dashMetric','data-value="usage"',v.dashMetric==='usage'?'selected small':'ghost small')}</div>`)}${dashPanel('使用權狀態分布','依目前所選產品，即時彙整',donutSvg(es,s,product))}</div><div class="dash-row-grid">${dashPanel('產品營運狀態','功能可用性與方案名額占用',health,link('管理產品 →','products'))}${dashPanel('額度使用排行','依使用比例排序，點選可調整',quotaChart,link('全部額度 →','quotas'))}</div><div class="dash-row-grid">${dashPanel('到期監控','已到期及未來 30 天內到期',`<table class="dash-table"><thead><tr><th>公司</th><th>產品</th><th>到期日</th><th>剩餘</th></tr></thead><tbody>${dueRows||'<tr><td colspan="4">目前沒有到期項目</td></tr>'}</tbody></table>`,link('查看全部 →','companies',`data-preset="到期／即將到期" data-product-filter="${product}"`))}${dashPanel('待處理佇列',`${s.tasks.filter(t=>t.state!=='已處理').length} 件未完成 · 按影響追蹤`,taskRows||'<div class="dash-empty">沒有待處理事項</div>',link('查看全部 →','tasks'))}</div>${dashPanel('最近發布紀錄','產品、版本、發布範圍與結果',`<table class="dash-table"><thead><tr><th>發布項目</th><th>產品</th><th>版本</th><th>狀態</th><th>時間</th></tr></thead><tbody>${releaseRows}</tbody></table>`,link('所有發布 →','releases'))}</div>`;
}
