import {notionDemoPanel,notionDemoAction} from './notion-demo.js';
import {DEMO_DATE} from './data.js';
import {esc,btn,link,status} from './ui.js';
import {companyOf,productOf} from './model.js';
import {table} from './screens.js';
import {initTasks} from './tasks.js';
const messageBtn=(label,a,attrs='',tone='secondary')=>btn(label,'message-'+a,attrs,tone);
export function initMessages(s){if(s.inbox)return;s.inbox={tab:'support',selected:'',notice:'',items:[
 {id:'msg1',kind:'support',company:'c1',product:'e2b',name:'陳柏宇',email:'contact1@client.example',subject:'圖片生成一直沒有完成',source:'E2B 系統內提問',state:'新訊息',owner:'林怡君',time:DEMO_DATE+' 15:10',context:'商品圖片生成 · 任務 DEMO-IMG-031 · 逾時',attachment:'操作截圖.png（附件名稱展示）',thread:[{actor:'客戶',text:'今天生成圖片一直停在處理中，重試後仍然沒有結果，可以協助確認嗎？',time:DEMO_DATE+' 15:10'}],draft:'',notes:[]},
 {id:'msg2',kind:'support',company:'c3',product:'e2b',name:'周庭安',email:'contact3@client.example',subject:'同事無法接受邀請',source:'E2B 系統內提問',state:'處理中',owner:'王小明',time:DEMO_DATE+' 10:20',context:'帳號邀請 · 公司共用 3 席方案',thread:[{actor:'客戶',text:'同事點邀請連結沒有成功，想了解是否與帳號名額有關。',time:DEMO_DATE+' 10:20'}],draft:'',notes:[]},
 {id:'msg3',kind:'inquiry',company:'',organization:'青禾商行',product:'e2b',name:'林小姐',email:'demo@prospect.example',subject:'想了解 E2B 試用與報價',source:'DS 自家官網諮詢表單',state:'新訊息',owner:'王小明',time:DEMO_DATE+' 14:30',context:'需求：商品內容製作 · 預計 5 人使用 · 希望安排 Demo',thread:[{actor:'訪客',text:'我們想改善商品內容製作流程，請問可以試用嗎？也想了解五個人使用的方案。',time:DEMO_DATE+' 14:30'}],draft:'',notes:[]},
 {id:'msg4',kind:'inquiry',company:'c2',product:'web',name:'李佳玲',email:'contact2@client.example',subject:'官網發布遇到問題',source:'DS 自家官網諮詢表單',state:'新訊息',owner:'張凱文',time:DEMO_DATE+' 11:45',context:'已辨識為既有客戶，適合轉使用支援',thread:[{actor:'客戶',text:'我們的網站更新沒有成功，從這邊留言可以請你們協助嗎？',time:DEMO_DATE+' 11:45'}],draft:'',notes:[]}
 ]};}
export function messagesPage(s,v){initMessages(s);const box=s.inbox,m=box.items.find(x=>x.id===box.selected);const tabs=`<div class="message-tabs">${['support','inquiry'].map((k,i)=>messageBtn(['使用支援','官網諮詢'][i],'tab',`data-tab="${k}" aria-pressed="${box.tab===k}"`,box.tab===k?'selected':'ghost')).join('')}</div>`;const note=`<div class="ops-demo-note"><b>客戶訊息 Demo</b><span>系統內問題與 DS 自家官網諮詢分流；不包含客戶自己的網站表單。訊息、附件與寄送皆為模擬。</span></div>${box.notice?`<div class="care-notice" role="status">${esc(box.notice)}</div>`:''}`;
if(!m)return note+tabs+`<div class="message-list-heading"><h2>${box.tab==='support'?'使用支援收件':'官網諮詢收件'}</h2><label>搜尋 <input id="pageSearch" value="${esc(v.query||'')}" placeholder="主旨、公司或聯絡人"></label></div>`+table(v,'messages',['收到時間','主旨／來源','公司／聯絡人','產品','負責人','狀態','操作'],box.items.filter(x=>x.kind===box.tab).sort((a,b)=>b.time.localeCompare(a.time)).map(x=>({search:x.subject+x.name+(x.company?companyOf(s,x.company).name:x.organization),cells:[x.time,`<b>${esc(x.subject)}</b><small>${esc(x.source)}</small>`,`${esc(x.company?companyOf(s,x.company).short:x.organization||'公司尚未確認')}<small>${esc(x.name)}</small>`,esc(productOf(s,x.product).name),esc(x.owner),status(x.state),messageBtn('查看訊息','open',`data-id="${x.id}"`,'small secondary')]})));
return note+`<div class="care-detail-nav">${messageBtn('← 返回訊息清單','back')}<span>${m.kind==='support'?'使用支援':'官網諮詢'} / ${esc(m.subject)}</span></div><section class="dash-panel"><header><div><h2>${esc(m.subject)} ${status(m.state)}</h2><p>${esc(m.source)} · ${esc(m.name)} · ${esc(m.email)}</p></div>${m.company?link('公司詳情 →','company',`data-id="${m.company}" data-product="${m.product}"`):'<span class="care-status">潛在客戶</span>'}</header><div class="message-context"><b>提問背景／需求</b><p>${esc(m.context)}</p>${m.attachment?`<small>附件：${esc(m.attachment)}</small>`:''}<div class="message-controls"><label>負責人<select data-message-field="owner">${s.staff.map(u=>`<option ${u.name===m.owner?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><label>處理狀態<select data-message-field="state">${(m.kind==='support'?['新訊息','處理中','等待客戶','已結案']:['新訊息','需求確認中','已安排展示','等待客戶','已結案']).map(x=>`<option ${x===m.state?'selected':''}>${x}</option>`).join('')}</select></label>${messageBtn('保存指派與進度','save')}</div><div class="message-controls">${messageBtn(m.kind==='support'?'轉為官網諮詢':'轉為使用支援','transfer')}${m.kind==='support'?messageBtn(m.task?'已建立營運待辦':'建立營運待辦','task',m.task?'disabled':'','primary'):''}${m.task?link('前往營運待辦 →','tasks'):''}</div></div>${notionDemoPanel(s,m)}<div class="care-section"><h3>訊息與回覆</h3>${m.thread.map(r=>`<article class="message-bubble"><small>${esc(r.actor)} · ${esc(r.time)}</small><p>${esc(r.text)}</p></article>`).join('')}<label>回覆草稿<textarea rows="5" data-message-field="draft" placeholder="輸入回覆內容">${esc(m.draft)}</textarea></label><div class="care-inline">${messageBtn('AI 建議回覆','draft')}${messageBtn('確認內容並模擬回覆','reply','','primary')}</div><p class="care-muted">AI 草稿為固定範例，人員確認後才執行模擬回覆，不會實際寄信。</p></div><div class="care-section"><h3>內部備註與處理紀錄</h3><label>內部備註<textarea rows="3" data-message-field="note" placeholder="只供內部人員查閱">${esc(m.note||'')}</textarea></label>${messageBtn('新增內部備註','note')}${m.notes.map(n=>`<p class="care-log"><small>${esc(n.time)}</small>${esc(n.text)}</p>`).join('')}</div></section>`;
}
export function messageAction(s,a,id,tab){initMessages(s);const box=s.inbox,m=box.items.find(x=>x.id===box.selected);box.notice='';if(a==='open')box.selected=id;if(a==='back')box.selected='';if(a==='tab'){box.tab=tab;box.selected='';}if(!m)return;if(a.startsWith('bug-'))return notionDemoAction(s,m,a.slice(4));
const log=text=>m.notes.unshift({time:DEMO_DATE+'（展示）',text});
if(a==='save'){log(`指派給 ${m.owner}，狀態：${m.state}`);box.notice='已保存本次展示的指派與處理進度。';}
if(a==='transfer'){m.kind=m.kind==='support'?'inquiry':'support';box.tab=m.kind;m.state='新訊息';log(`轉為${m.kind==='support'?'使用支援':'官網諮詢'}；保留原始來源與訊息串。`);box.notice='已轉接，原訊息與紀錄保留。';}
if(a==='draft'){m.draft=m.kind==='support'?`${m.name}您好，我們已收到您反映的問題，會協助確認。若方便，請補充發生時間與操作步驟，讓我們進一步排查。`:`${m.name}您好，謝謝您對我們產品的關注。想進一步了解團隊的使用需求與預計導入時間，以便安排合適的產品展示與方案說明。`;box.notice='已產生回覆草稿（模擬），請確認內容。';}
if(a==='reply'){if(!m.draft.trim()){box.notice='請先填寫回覆內容。';return;}m.thread.push({actor:`${m.owner}（模擬回覆）`,time:DEMO_DATE+'（展示）',text:m.draft});m.draft='';m.state='等待客戶';log('已確認並模擬回覆，等待客戶回覆。');box.notice='已模擬回覆，訊息串已更新。';}
if(a==='note'){if(!m.note?.trim()){box.notice='請先填寫內部備註。';return;}log(m.note);m.note='';}
if(a==='task'){if(m.task)return;initTasks(s);m.task='message-task-'+Date.now();s.tasks.unshift({id:m.task,title:m.subject,desc:`使用支援案件：${m.name}，${m.context}`,category:'客戶服務',product:m.product,owner:m.owner,priority:'中',state:'待處理',next:'確認客戶問題，執行處置並回覆原訊息',destination:m.company?'company':'product',destinationId:m.company||m.product,created:DEMO_DATE,updated:DEMO_DATE,notes:[],message:m.id});log('已建立營運待辦，與此訊息關聯。');box.notice='已建立一筆營運待辦；重複點擊不會重複建立。';}
}

