import {DEMO_DATE} from './data.js';
import {companyOf,productOf} from './model.js';
import {esc,btn,link,status} from './ui.js';
import {table} from './screens.js';
export function initTasks(s){if(s.tasksPrepared)return;s.tasksPrepared=true;const definitions=[
 ['產品維運','內容版型檢查失敗','活動橫幅版型缺少必要檔案，發布前需修正並重新檢查。','web','張凱文','修正版型並重新檢查','asset',''],
 ['客戶服務','客戶即將到期','綠沐生活官網使用權將於 2026-10-21 到期，需確認續約與服務期限。','web','張凱文','確認續約並更新期限','company','c2'],
 ['產品維運','功能維護中','E2B 訂單同步功能維護中，需追蹤恢復狀況與影響。','e2b','林怡君','確認功能恢復與公告','product','e2b'],
 ['客戶服務','等待開通','晨港物流官網服務等待開通，需確認方案與開通條件。','web','王小明','確認條件後開通服務','company','c3'],
 ['帳務與額度','付款逾期','曜石工業 E2B 付款逾期，需確認付款與公司暫停狀態。','e2b','林怡君','確認付款並記錄處置','company','c6'],
 ['帳務與額度','額度接近上限','綠沐生活網站發布已用 46 / 50 次，需確認剩餘需求。','web','張凱文','確認需求與調整額度','quotas','c2']
 ];s.tasks.forEach((t,i)=>{const d=definitions[i];if(!d)return;Object.assign(t,{category:d[0],title:d[1],desc:d[2],product:d[3],owner:d[4],next:d[5],destination:d[6],destinationId:d[7],created:DEMO_DATE,updated:DEMO_DATE,notes:[]});if(t.destination==='asset')t.destinationId=s.blocks.find(b=>b.status==='檢查失敗')?.id||s.blocks[0]?.id;});}
export function taskDestination(s,t){if(t.destination==='quotas')return btn('前往額度管理','quotaDrill',`data-product="${t.product}" data-company="${t.destinationId}"`,'small secondary');return link(t.destination==='asset'?'前往版型檢查':t.destination==='product'?'前往產品功能':'前往公司服務',t.destination||'products',`data-id="${t.destinationId||''}" data-product="${t.product}"`);}
export function tasksPage(s,v){initTasks(s);const category=v.taskCategory||'all',state=v.taskState||'open';let list=s.tasks.filter(t=>(category==='all'||t.category===category)&&(state==='all'||state==='open'?state==='all'||t.state!=='已處理':t.state===state));list.sort((a,b)=>(a.state==='已處理')-(b.state==='已處理')||({'高':0,'中':1,'低':2}[a.priority]??3)-({'高':0,'中':1,'低':2}[b.priority]??3));return `<div class="ops-demo-note"><b>营運待辦 Demo</b><span>追蹤內部人員需要執行的工作；前往對應管理頁完成實際調整，再更新處理紀錄。</span></div><div class="task-controls"><label>工作類型 <select data-view="taskCategory">${[['all','全部類型'],...['產品維運','客戶服務','帳務與額度'].map(x=>[x,x])].map(([id,n])=>`<option value="${id}" ${category===id?'selected':''}>${n}</option>`).join('')}</select></label><label>處理狀態 <select data-view="taskState">${[['open','尚未完成'],['all','全部'],...['待處理','處理中','已處理'].map(x=>[x,x])].map(([id,n])=>`<option value="${id}" ${state===id?'selected':''}>${n}</option>`).join('')}</select></label><label>搜尋 <input id="pageSearch" value="${esc(v.query||'')}" placeholder="事項、負責人或產品"></label></div>${table({...v,sort:'default'},'operationsTasks',['工作／處理目標','類型','產品','優先序','負責人','進度','操作'],list.map(t=>({search:t.title+' '+t.desc+' '+t.owner+' '+productOf(s,t.product).name,cells:[`<b>${esc(t.title)}</b><small>${esc(t.desc)}</small><small>下一步：${esc(t.next)}</small>`,esc(t.category),esc(productOf(s,t.product).name),status(t.priority,t.priority==='高'?'bad':'warn'),esc(t.owner),`${status(t.state)}<small>更新 ${esc(t.updated)}</small>`,taskDestination(s,t)+btn('更新進度','task',`data-id="${t.id}"`,'small secondary')]})))}<p class="chart-footnote">低使用與功能推薦由${link('客戶關懷','care')}追蹤。更新待辦為「已處理」只記錄進度，不會自動開通、恢復服務或調整額度。這些事項為展示資料，尚未接事件自動產生。</p>`;}
