import { readFile,writeFile } from 'node:fs/promises';
const files=['legacy.js','data.js','model.js','ui.js','screens.js','assets.js','restore.js','dashboard.js','dialogs.js','main.js'];
const parts=[];
for(const file of files){const source=await readFile(new URL('./src/'+file,import.meta.url),'utf8');parts.push('// '+file+'\n'+source.replace(/^import .*?;\r?\n/gm,'').replace(/^export /gm,''));}
await writeFile(new URL('./src/app.bundle.js',import.meta.url),'/* Generated by node build.js; supports direct file opening. */\n(()=>{\n"use strict";\n'+parts.join('\n')+'\n})();\n');
console.log('Built src/app.bundle.js');
