import assert from 'node:assert/strict';
import {seedState} from './src/data.js';
import {entitlementOf,seats,canActivate,accountAccess,featureAccess} from './src/model.js';
const s=seedState();
const c1e=s.users.find(u=>u.company==='c1'&&u.product==='e2b'&&u.status==='啟用');
const c1w=s.users.find(u=>u.company==='c1'&&u.product==='web'&&u.status==='啟用');
assert.equal(accountAccess(s,c1e).label,'可使用');
assert.equal(accountAccess(s,c1w).label,'不可使用');
const full=entitlementOf(s,'c3','e2b');
assert.deepEqual(seats(s,full),{active:2,invited:1,inactive:1,used:3,limit:3,remaining:0});
const off=s.users.find(u=>u.company==='c3'&&u.status==='停用');
assert.equal(canActivate(s,off).ok,false);
s.users.find(u=>u.company==='c3'&&u.status==='啟用').status='停用';
assert.equal(canActivate(s,off).ok,true);
s.companies.find(c=>c.id==='c1').enabled=false;
assert.equal(accountAccess(s,c1e).label,'不可使用');
s.companies.find(c=>c.id==='c1').enabled=true;
s.products.find(p=>p.id==='e2b').enabled=false;
assert.equal(featureAccess(s,'c1',s.features[0]).label,'不可使用');
assert.equal(accountAccess(s,s.users.find(u=>u.company==='c8'&&u.product==='web'&&u.status==='啟用')).label,'可使用');
for(const e of s.entitlements)assert.ok(seats(s,e).used<=seats(s,e).limit);
const t=seedState();
const f=t.features.find(f=>f.id==='f6');
assert.equal(featureAccess(t,'c3',f).label,'不可使用');
f.scope='全部客戶';
assert.equal(featureAccess(t,'c3',f).label,'可使用');
f.scope='僅內部測試';
assert.equal(featureAccess(t,'c1',f).label,'不可使用');
assert.equal(featureAccess(t,'c3',t.features.find(f=>f.id==='f8')).label,'不可使用');
assert.equal(featureAccess(t,'c4',t.features.find(f=>f.id==='f5')).label,'不可使用');
entitlementOf(t,'c1','e2b').start='2026-12-01';
assert.equal(accountAccess(t,t.users.find(u=>u.company==='c1'&&u.product==='e2b'&&u.status==='啟用')).label,'不可使用');
console.log('Passed: product isolation, invited seats, reactivation limit, suspension, audience scopes, quota, overrides, future term.');
