import {companyEntitlements} from './src/screens.js';
import assert from 'node:assert/strict';
import {legacySnapshot} from './src/legacy.js';
import {executeRestore} from './src/restore.js';
import {seedState} from './src/data.js';
import {entitlementOf,seats,canActivate,accountAccess,featureAccess} from './src/model.js';
const s=seedState();
const c1e=s.users.find(u=>u.company==='c1'&&u.product==='e2b'&&u.status==='啟用');
const c1w=s.users.find(u=>u.company==='c1'&&u.product==='web'&&u.status==='啟用');
assert.equal(accountAccess(s,c1e).label,'可使用');
assert.equal(accountAccess(s,c1w).label,'不可使用');
const full=entitlementOf(s,'c3','e2b');
assert.deepEqual(seats(s,full),{active:2,invited:1,inactive:1,used:3,limit:3,remaining:0});
const off=s.users.find(u=>u.company==='c3'&&u.status==='停用');
assert.equal(canActivate(s,off).ok,false);
s.users.find(u=>u.company==='c3'&&u.status==='啟用').status='停用';
assert.equal(canActivate(s,off).ok,true);
s.companies.find(c=>c.id==='c1').enabled=false;
assert.equal(accountAccess(s,c1e).label,'不可使用');
s.companies.find(c=>c.id==='c1').enabled=true;
s.products.find(p=>p.id==='e2b').enabled=false;
assert.equal(featureAccess(s,'c1',s.features[0]).label,'不可使用');
assert.equal(accountAccess(s,s.users.find(u=>u.company==='c8'&&u.product==='web'&&u.status==='啟用')).label,'可使用');
for(const e of s.entitlements)assert.ok(seats(s,e).used<=seats(s,e).limit);
const t=seedState();
const f=t.features.find(f=>f.id==='f6');
assert.equal(featureAccess(t,'c3',f).label,'不可使用');
f.scope='全部客戶';
assert.equal(featureAccess(t,'c3',f).label,'可使用');
f.scope='僅內部測試';
assert.equal(featureAccess(t,'c1',f).label,'不可使用');
assert.equal(featureAccess(t,'c3',t.features.find(f=>f.id==='f8')).label,'不可使用');
assert.equal(featureAccess(t,'c4',t.features.find(f=>f.id==='f5')).label,'不可使用');
entitlementOf(t,'c1','e2b').start='2026-12-01';
assert.equal(accountAccess(t,t.users.find(u=>u.company==='c1'&&u.product==='e2b'&&u.status==='啟用')).label,'不可使用');
console.log('Passed: product isolation, invited seats, reactivation limit, suspension, audience scopes, quota, overrides, future term.');
const restored=seedState();
for(const f of legacySnapshot.features)assert.ok(restored.features.some(x=>x.code===f.code),'Missing original feature '+f.code);
for(const a of legacySnapshot.templates)assert.ok([...restored.brands,...restored.blocks].some(x=>x.code===a.code),'Missing original asset '+a.code);
for(const q of restored.quotas)assert.equal(restored.usageByUser.filter(u=>u.quota===q.id).reduce((n,u)=>n+u.used,0),q.used);
assert.throws(()=>executeRestore('submitEntitlementEdit',{id:'en1'},{plan:'plan-e3',start:'2026-01-01',end:'2027-01-01'},restored,()=>{}),/超過/);
const staffResult=executeRestore('submitLegacyStaff',{}, {name:'QA',email:'qa@example.com',department:'QA',role:'測試',scope:'唯讀',actions:['檢視'],modules:[],reason:'檢查'},restored,()=>{});
assert.ok(staffResult);assert.equal(restored.staff.at(-1).status,'邀請中');
console.log('Passed: original features/assets preserved, user usage totals, downgrade limit, staff creation.');

const planState=seedState(),planPayload={name:'E2B · 3 席方案',code:'plan-e3',limit:2,billing:'公司訂閱（月繳）',price:'',status:'可供選用',note:'',reason:'驗證名額保護'};
assert.throws(()=>executeRestore('submitPlanEdit',{id:'plan-e3'},planPayload,planState,()=>{}),/帳號上限低於/);
assert.equal(planState.plans.find(p=>p.id==='plan-e3').limit,3);
executeRestore('submitPlanEdit',{id:'plan-e3'},{...planPayload,limit:4,status:'停止新選用'},planState,()=>{});
assert.equal(seats(planState,entitlementOf(planState,'c3','e2b')).limit,4);
assert.equal(entitlementOf(planState,'c3','e2b').enabled,true);
assert.throws(()=>executeRestore('submitCompanyEdit',{}, {product:'e2b',plan:'plan-e3',code:'NEW',start:'2026-10-05',end:'2027-10-04'},planState,()=>{}),/可供選用/);
assert.throws(()=>executeRestore('submitPlanEdit',{}, {...planPayload,product:'web',code:'plan-w3',limit:5},planState,()=>{}),/相同方案代碼/);
console.log('Passed: product plan cap protection, existing subscriptions preserved, retired plans block new selection, duplicate product plan codes.');

const companyState=seedState(),splitCompany=companyState.companies.find(c=>c.id==='c1');
assert.equal(companyEntitlements(companyState,{productFilter:'e2b',filter:'已到期'},splitCompany).length,0);
assert.equal(companyEntitlements(companyState,{productFilter:'web',filter:'已到期'},splitCompany).length,1);
assert.equal(companyEntitlements(companyState,{productFilter:'all',filter:'全部'},splitCompany).length,2);
assert.equal(companyEntitlements(companyState,{productFilter:'e2b',filter:'有效使用權'},splitCompany).length,1);
console.log('Passed: company product/status filters apply to the same entitlement, grouped rights preserved.');
