import { DEMO_DATE } from './data.js';
import { companyOf,productOf } from './model.js';
import { esc,status,btn,link,section,field,select,note,steps,tabs } from './ui.js';
import { table,toolbar } from './screens.js';
export function assetOf(s,id) {return s.brands.find(a=>a.id===id)||s.blocks.find(a=>a.id===id);}
export function assetKind(s,id) {return s.brands.some(a=>a.id===id)?'brand':'block';}
export function affectedSites(s,id) {return s.websites.filter(w=>w.brand===id||w.blocks.includes(id));}
export function sitePreview(brand,block,device='desktop') {
  const color=brand?.color||'#185b79';const serif=brand?.font?.includes('Serif');
  const body=block?`<section><small>OUR SERVICES</small><h1>${esc(block.name.split(' · ')[0])}</h1><p>${esc(block.description)}</p>${block.category==='聯絡表單'?'<label>姓名<input placeholder="您的姓名"></label><label>Email<input placeholder="name@example.com"></label><button>送出訊息</button>':block.category==='品牌故事'?`<div class="story"><div class="story-media" aria-label="品牌圖片位置示意"><span>BRAND / STORY</span></div><div><small>SINCE 2016</small><h2>每一份細節，<br>都是我們的承諾。</h2><p>從一個想法開始，讓專業與溫度成為品牌的日常。這裡呈現可編輯的品牌故事內文，以及圖片與文字交錯的內容結構。</p><a>認識我們 →</a></div></div>`:`<div class="services"><article><span>01</span><h2>專業服務</h2><p>從需求出發，提供合適的解決方案。</p><a>了解更多 →</a></article><article><span>02</span><h2>長期合作</h2><p>持續陪伴您的品牌，讓每一步更清楚。</p><a>了解更多 →</a></article><article><span>03</span><h2>品質承諾</h2><p>以細節與一致的品質，建立信任。</p><a>了解更多 →</a></article></div>`}</section>`:`<section class="hero"><small>YOUR BRAND, CLEARLY EXPRESSED</small><h1>讓品牌的每一步，<br>都有一致的樣貌。</h1><p>以清晰的設計、細緻的服務，<br>連結每一次重要的相遇。</p><button>認識我們 →</button></section><section><small>ABOUT US</small><h2>用細節，建立長久的信任。</h2><p>這是用來比較品牌色、文字層級與元件的網站示意。</p><div class="services"><article><h2>品牌理念</h2><p>清晰而有溫度的溝通。</p></article><article><h2>專業服務</h2><p>從每一個需求出發。</p></article></div></section>`;
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;color:#223231;background:#fcfcf9;font-family:${serif?'Georgia,"Microsoft JhengHei",serif':'"Microsoft JhengHei",sans-serif'};font-size:14px}header{display:flex;align-items:center;justify-content:space-between;padding:20px 6%;border-bottom:1px solid #e3e6e1}header b{font-size:19px;color:${color}}nav{font-size:12px;color:#667673}section{padding:40px 7%}section.hero{background:${color};color:white;padding:55px 7%}small{font-size:10px;letter-spacing:2px;opacity:.7}h1{font-size:36px;font-weight:500;line-height:1.6;letter-spacing:1px;margin:12px 0}h2{font-size:20px;font-weight:500}p{line-height:1.9;opacity:.75}button{border:0;background:${color};color:white;padding:12px 22px;border-radius:2px}.hero button{background:white;color:${color};margin-top:12px}.services{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin-top:24px}.services article{border-top:2px solid ${color};padding-top:16px}.services span{color:${color}}a{font-size:12px;color:${color}}.story{display:grid;grid-template-columns:1fr 1fr;gap:36px;align-items:center;margin-top:30px}.story-media{height:240px;background:linear-gradient(140deg,#e2e9e2 50%,#c2d0c6 50%);display:flex;align-items:end;padding:24px}.story-media span{font-size:12px;letter-spacing:3px;color:#4d675b}label{display:block;margin:14px 0}input{display:block;border:1px solid #ddd;padding:12px;width:100%;margin-top:6px}footer{border-top:1px solid #ddd;padding:20px 7%;font-size:11px;color:#888}@media(max-width:450px){nav{display:none}h1{font-size:25px}section,section.hero{padding:30px 7%}.services{grid-template-columns:1fr;gap:12px}header{padding:15px 7%}.story{grid-template-columns:1fr;gap:20px}.story-media{height:180px}}</style></head><body><header><b>BRAND STUDIO</b><nav>關於我們　服務介紹　最新消息　聯絡我們</nav></header>${body}<footer>© 2026 Brand Studio · 品牌樣式／內容結構示意</footer></body></html>`;
}
export function assetList(s,v) {
  const brand=v.page==='brands';const list=(brand?s.brands:s.blocks).filter(a=>v.filter==='全部'||a.status===v.filter);
  return `<div class="asset-intro"><div><span class="eyebrow">${brand?'BRAND LANGUAGE':'CONTENT STRUCTURE'}</span><h2>${brand?'一套樣式，保持所有網站的一致。':'讓內容，有合適的呈現方式。'}</h2><p>${brand?'色彩、字體與元件風格。更新後，所有採用網站會同步生效。':'頁面區塊的結構、欄位與排列。與網站品牌視覺分開管理。'}</p></div><span class="asset-count">${list.length}<small>${brand?'套品牌樣式':'個內容版型'}</small></span></div>`+toolbar(v,['已發布','測試中','檢查失敗','草稿','已下架'])+table(v,brand?'brands':'blocks',[brand?'品牌樣式':'內容版型',brand?'視覺規格':'內容結構','版本','狀態','採用網站','更新','操作'],list.map(a=>({search:`${a.name} ${a.code}`,cells:[`<div class="asset-name">${brand?`<span class="color-swatch" style="background:${a.color}"></span>`:`<span class="block-label">${a.category.slice(0,2)}</span>`}<div>${link(a.name,'asset',`data-id="${a.id}"`)}<small class="mono">${a.code}</small></div></div>`,brand?`<div class="palette"><span style="background:${a.color}"></span><span style="background:#e9eeeb"></span><span style="background:#172f35"></span></div><small>${a.font}</small>`:`<b>${a.layout}</b><small>${a.description}</small>`,`<span class="mono">${a.version}</span>`,status(a.status),`${affectedSites(s,a.id).length} 個網站`,`<span class="mono">${a.updated}</span><small>${a.owner}</small>`,btn('查看階段','openAsset',`data-id="${a.id}"`,'small ghost')]})))+note(brand?'品牌樣式發布為全域更新，沒有「只更新部分採用網站」的選項。':'內容版型的自動升級與內容保留規則尚待確認；展示畫面提供影響與版本差異供討論。');
}
export function assetDetail(s,v) {
  const a=assetOf(s,v.id);if(!a)return note('找不到資產，請回到清單重新選擇。');const brand=assetKind(s,a.id)==='brand';
  return `<div class="detail-identity"><div><span class="eyebrow">${brand?'品牌樣式':'內容版型'} / ${a.code}</span><h2>${a.name}</h2><p>${a.description} · ${a.owner}</p></div><div class="identity-actions">${status(a.status)}<span class="version">${a.version}</span>${btn('建立新版','newAsset',`data-kind="${brand?'brand':'block'}" data-id="${a.id}"`,'primary')}</div></div>`+tabs([['definition','基本資料'],['checks','檢查結果'],['preview','桌機／手機預覽'],['testing','測試'],['publishing','發布與影響'],['versions','歷史版本']],v.assetTab,'assetTab')+assetTab(s,v,a,brand);
}
function siteTable(s,v,a) {return table(v,'affectedSites',['採用網站','所屬公司','目前版本','操作'],affectedSites(s,a.id).map(w=>({search:w.name,cells:[`<b>${w.name}</b><small class="mono">${w.domain}</small>`,link(companyOf(s,w.company).short,'company',`data-id="${w.company}"`),w.version,btn('預覽示意','previewSite',`data-id="${w.id}"`,'small ghost')]})),{footer:false});}
function previewBody(s,v,a,brand) {const b=brand?a:s.brands.find(b=>b.id==='b1');const bl=brand?null:a;return `<div class="preview-controls"><div>${btn('桌機','previewDevice','data-device="desktop"',v.device==='desktop'?'selected':'ghost')}${btn('手機','previewDevice','data-device="mobile"',v.device==='mobile'?'selected':'ghost')}</div><span>同一份示意內容 · ${brand?'比較品牌色／字體／元件':'檢查內容結構／手機排列'}</span></div><div class="preview-workspace ${v.device}"><div class="preview-browser"><div class="browser-chrome"><span></span><span></span><span></span><b>品牌與內容預覽 · 展示</b></div><iframe title="${a.name}${v.device==='mobile'?'手機':'桌機'}預覽" sandbox srcdoc="${esc(sitePreview(b,bl,v.device))}"></iframe></div></div>`;}
function checkRows(failure) {return `<div class="check-results">${[['入口檔案','找到 index.html',true],['資源與字型','CSS、JavaScript、字型引用完整',true],['可編輯欄位',failure?'schema.json 缺少 contact.email 欄位':'欄位定義與內容結構一致',!failure],['外部資源','未發現未允許的外部 Script',true],['響應式布局','桌機與手機示意均可顯示',true],['官網相容性','相容於官網系統 v1.6.x',true]].map(([name,detail,ok])=>`<div><span class="check-symbol ${ok?'ok':'bad'}">${ok?'通過':'失敗'}</span><b>${name}</b><span>${detail}</span></div>`).join('')}</div>`;}
function assetTab(s,v,a,brand) {
  if(v.assetTab==='checks')return `<div class="section-heading"><div><h2>檔案檢查明細</h2><p>結果為預設展示情境，可切換通過或失敗。</p></div><select aria-label="檢查結果情境" data-view="checkScenario"><option value="pass" ${v.checkScenario==='pass'?'selected':''}>檢查通過</option><option value="fail" ${v.checkScenario==='fail'?'selected':''}>檢查失敗</option></select></div>`+note(v.checkScenario==='fail'?'檢查失敗：請修正欄位定義後重新送出檢查。':'檢查通過，可進入預覽與測試。',v.checkScenario==='fail'?'bad':'success')+checkRows(v.checkScenario==='fail');
  if(v.assetTab==='preview')return previewBody(s,v,a,brand);
  if(v.assetTab==='testing')return section('測試版本','正式版本維持不變，另行展示新版測試。',`<div class="definition-row"><span>目前正式版本</span><b>${a.version}</b></div><div class="definition-row"><span>測試版本</span><b>${a.pendingVersion||a.versions[0]} · ${status(a.pendingStage||'測試中')}</b></div><div class="definition-row"><span>指定測試公司</span><b>遠星科技、禾境設計</b></div>`)+note(brand?'測試預覽不代表正式發布。正式發布後仍會一次更新所有採用網站。':'指定客戶測試與正式發布分開呈現。')+previewBody(s,v,a,brand);
  if(v.assetTab==='publishing')return `<div class="publish-lead"><div><span class="eyebrow">${brand?'GLOBAL BRAND UPDATE':'CONTENT RELEASE'}</span><h2>${brand?'所有採用網站，將一起更新。':'先確認內容結構，再確認發布。'}</h2><p>${brand?'品牌樣式的色彩、字體與元件變更會影響各網站整體。':'版型影響的頁面、欄位與內容保留方式需由此畫面確認。'}</p></div><strong>${affectedSites(s,a.id).length}<small>採用網站</small></strong></div>`+siteTable(s,v,a)+note(brand?'不提供部分網站發布；確認後所有採用網站同步更新。':'內容版型更新與更換規則仍待確認。此處展示確認畫面，不自動改動客戶內容。',brand?'warn':'info')+`<div class="action-footer">${btn('查看下架情境','assetRetire',`data-id="${a.id}"`,'danger-outline')}${btn(brand?'確認品牌樣式更新':'查看發布確認','assetPublish',`data-id="${a.id}"`,'primary')}</div>`;
  if(v.assetTab==='versions')return section('版本時間軸','保留正式與歷史版本，供檢視、比較與回復。',`<div class="version-timeline">${a.versions.map((ver,i)=>`<div><span class="timeline-dot"></span><div><b class="mono">${ver}</b>${status(ver===a.version?'目前採用':'歷史版本',ver===a.version?'ok':'info')}<p>${ver===a.version?'目前採用版本':'版本紀錄，供回復情境展示'}</p><small>${a.owner} · ${i===0?a.updated:'2026-09-12'}</small></div><div>${btn('預覽','assetVersionPreview',`data-id="${a.id}" data-version="${ver}"`,'small ghost')}${ver!==a.version?btn('回復確認','assetRollback',`data-id="${a.id}" data-version="${ver}"`,'small ghost'):''}</div></div>`).join('')}</div>`);
  return section(brand?'品牌視覺定義':'內容欄位定義',brand?'控制全站的視覺語言，不負責內容區塊結構。':'控制內容區塊的結構，不取代品牌色與字體。',`<dl class="definition-grid"><div><dt>名稱</dt><dd>${a.name}</dd></div><div><dt>代碼</dt><dd class="mono">${a.code}</dd></div><div><dt>版本</dt><dd class="mono">${a.version}</dd></div><div><dt>${brand?'品牌色':'呈現方式'}</dt><dd>${brand?`<span class="color-swatch small" style="background:${a.color}"></span> ${a.color}`:a.layout}</dd></div><div><dt>${brand?'字體':'可編輯欄位'}</dt><dd>${brand?a.font:'標題、摘要、內文、連結、圖片'}</dd></div><div><dt>${brand?'元件樣式':'固定結構'}</dt><dd>${brand?'按鈕、輸入框、標題與導覽':'區塊排列、欄位型別、手機布局'}</dd></div></dl>`)+section('檔案結構','此為套件內容示意。',`<div class="file-tree"><code>${brand?'brand-package.zip<br>├─ theme.json<br>├─ tokens.css<br>├─ components.css<br>└─ preview.html':'content-package.zip<br>├─ schema.json<br>├─ block.html<br>├─ block.css<br>└─ preview.html'}</code><div><b>${brand?'品牌樣式套件':'內容版型套件'}</b><p>上傳、檢查與預覽畫面可分階段展示。</p>${btn('查看上傳階段','newAsset',`data-kind="${brand?'brand':'block'}" data-id="${a.id}"`)}</div></div>`);
}
export function wizardPage(s,v) {
  const w=v.wizard;const brand=w.kind==='brand';const a=assetOf(s,w.source)||{name:brand?'新品牌樣式':'新內容版型',code:brand?'BRAND-NEW':'BLOCK-NEW',color:'#185b79',font:'Noto Sans TC',category:'服務入口',description:'新增資產的階段示意'};
  let body='';
  if(w.step===0)body=`<div class="form-columns"><div class="form-fields">${field('名稱','assetName',w.name||a.name,'text','required')}${field('資產代碼','assetCode',w.code||a.code,'text','required')}${field('新版本','assetVersion',w.version||'v1.5.0','text','required')}${field('負責人','assetOwner',w.owner||'張凱文')}${brand?field('品牌色','assetColor',w.color||a.color,'color'):select('內容類型','assetCategory',['服務入口','品牌故事','聯絡表單'],w.category||a.category)}<label class="field"><span>更新說明</span><textarea name="assetDescription">${esc(w.description||'調整視覺細節與手機呈現。')}</textarea></label></div><aside class="form-aside"><span class="eyebrow">${brand?'BRAND':'CONTENT'}</span><h3>${brand?'全站視覺的共同來源':'內容呈現的結構定義'}</h3><p>${brand?'品牌樣式更新將影響所有採用網站。':'內容版型需要定義欄位、固定結構與相容性。'}</p>${note('可直接切換上方階段，查看預設畫面；無需真的上傳檔案。')}</aside></div>`;
  if(w.step===1)body=`<div class="upload-stage"><div><span class="eyebrow">PACKAGE UPLOAD</span><h3>上傳${brand?'品牌樣式':'內容版型'}套件</h3><p>HTML 單檔或 ZIP · 選檔只讀取名稱，不會上傳到外部服務。</p><label class="file-picker">選擇本機檔案<input type="file" accept=".zip,.html,.htm" name="assetFile"></label>${btn('使用展示檔案','demoFile','','ghost')}</div><div class="upload-file"><b>${esc(w.file||'尚未選擇檔案')}</b><small>${w.file?'檔案已就緒 · 展示解析結果':'可選擇檔案，或載入預設展示套件'}</small><div class="usage-bar"><span style="width:${w.file?'100':'0'}%"></span></div></div></div>`+(w.file?`<div class="file-tree"><code>${brand?'theme.json<br>tokens.css<br>components.css<br>preview.html':'schema.json<br>block.html<br>block.css<br>preview.html'}</code><p>解析後的檔案結構示意</p></div>`:'');
  if(w.step===2)body=`<div class="section-heading"><div><h2>檢查結果</h2><p>預設結果可切換，不執行真實檔案掃描。</p></div><select aria-label="檢查結果情境" data-view="checkScenario"><option value="pass" ${v.checkScenario==='pass'?'selected':''}>檢查通過</option><option value="fail" ${v.checkScenario==='fail'?'selected':''}>檢查失敗</option></select></div>`+note(v.checkScenario==='fail'?'檢查失敗，無法正式發布。請修正套件並重新檢查。':'檢查通過，可查看預覽與發布影響。',v.checkScenario==='fail'?'bad':'success')+checkRows(v.checkScenario==='fail');
  if(w.step===3)body=previewBody(s,v,{...a,name:w.name||a.name,color:w.color||a.color},brand);
  if(w.step===4)body=note(brand?'正式發布會同步更新所有採用網站；測試公司選擇只影響測試預覽。':'指定公司測試與正式發布分開；內容保留策略仍待確認。')+`<div class="form-fields narrow">${select('階段','assetStage',['草稿','測試中','待發布'],w.stage||'待發布')}${field('預定發布時間','assetTime',w.time||'2026-10-06T10:00','datetime-local')}<fieldset><legend>測試公司</legend>${s.companies.filter(c=>s.entitlements.some(e=>e.company===c.id&&e.product==='web')).map(c=>`<label class="checkbox"><input name="testCompanies" type="checkbox" value="${c.id}" ${(w.clients||['c1','c7']).includes(c.id)?'checked':''}>${c.short}</label>`).join('')}</fieldset></div>`;
  return `<div class="workflow-title"><span class="eyebrow">${brand?'品牌樣式':'內容版型'} / 階段展示</span><h2>${w.source?'建立新版本':'建立資產'}</h2><p>各階段可直接切換，確認資料、檢查結果與發布影響。</p></div>`+steps(['基本資料','套件上傳','檢查結果','預覽','測試與發布'],w.step)+`<form id="wizardForm">${body}<div class="action-footer"><div>${btn('返回資產清單','cancelWizard','','ghost')}${w.step>0?btn('上一階段','wizardStep',`data-step="${w.step-1}"`):''}</div>${w.step<4?btn('下一階段 →','wizardStep',`data-step="${w.step+1}"`,'primary'):btn(w.stage&&w.stage!=='待發布'?'儲存展示階段':'查看發布影響','wizardFinish','','primary')}</div></form>`;
}
export function releaseDetail(s,v) {const r=s.releases.find(r=>r.id===v.id);if(!r)return note('找不到發布紀錄。');const stage=v.releaseStage||r.status;const a=assetOf(s,r.asset);const affected=a?affectedSites(s,a.id):s.entitlements.filter(e=>e.product===r.product);return `<div class="detail-identity"><div><span class="eyebrow">${r.type} / ${r.version}</span><h2>${r.name}</h2><p>${productOf(s,r.product).name} · ${r.owner} · ${r.time}</p></div>${status(stage)}</div>`+tabs(['草稿','測試中','待發布','已發布','發布失敗','已取消'].map(x=>[x,x]),stage,'releaseStage')+`<div class="release-layout"><div>${section('發布內容','清楚描述本次變更。',`<p class="body-text">${esc(r.description)}</p><dl class="definition-grid"><div><dt>版本</dt><dd>${r.version}</dd></div><div><dt>開放範圍</dt><dd>${r.scope}</dd></div><div><dt>預定時間</dt><dd>${r.time}</dd></div><div><dt>發布人員</dt><dd>${r.owner}</dd></div></dl>`)}${section('發布檢查','階段切換為預設展示，不代表實際部署。',checkRows(stage==='發布失敗'))}</div><aside class="release-aside"><span class="eyebrow">發布進度</span><ol class="vertical-steps">${['建立草稿','檢查與測試','確認影響','發布結果'].map((x,i)=>`<li class="${['已發布','發布失敗'].includes(stage)||i<2?'done':''}"><span>0${i+1}</span><b>${x}</b></li>`).join('')}</ol>${note(stage==='發布失敗'?'發布失敗示意：相容性檢查未通過，正式版本保持原狀。':stage==='已發布'?'已發布結果示意；可在歷史版本畫面查看回復確認。':`目前展示：${stage}`,stage==='發布失敗'?'bad':'info')}<p>${affected.length} ${a?'個採用網站':'間產品客戶'}</p>${a?link('查看資產與影響 →','asset',`data-id="${a.id}"`):link('查看產品 →','product',`data-id="${r.product}"`)}</aside></div>`;}
