import { DEMO_DATE } from './data.js';
import { companyOf,productOf,entitlementOf,seats,members,canActivate,serviceStatus,featureAccess } from './model.js';
import { esc,status,btn,section,field,select,note } from './ui.js';
import { assetOf,assetKind,affectedSites,sitePreview } from './assets.js';
function reason(value='') {return `<label class="field"><span>操作原因 <em>必填</em></span><textarea name="reason" required placeholder="說明本次調整原因">${esc(value)}</textarea></label>`;}
function diff(before,after) {return `<div class="diff"><div><span>變更前</span><b>${before}</b></div><div><span>變更後</span><b>${after}</b></div></div>`;}
function impact(items) {return `<dl class="impact-list">${items.map(([name,value])=>`<div><dt>${name}</dt><dd>${value}</dd></div>`).join('')}</dl>`;}
function confirmCheck() {return `<label class="checkbox confirm-check"><input name="confirm" type="checkbox" required>我已確認操作範圍與影響</label>`;}
export function dialogBody(s,v) {
  const m=v.modal;if(!m)return null;const d=m.data||{};let title='',subtitle='',body='',footer='',wide=false,drawer=true;
  if(m.type==='sensitive') {
    drawer=false;let target,before,after,items=[],blocked='';const kind=m.kind;
    if(kind==='company'){const c=companyOf(s,m.id);target=c.name;before=c.enabled?'公司正常':'公司已暫停';after=c.enabled?'整間公司暫停':'解除公司暫停';title=c.enabled?'暫停整間公司':'恢復整間公司';items=[['操作層級','公司'],['影響產品',s.entitlements.filter(e=>e.company===c.id).map(e=>productOf(s,e.product).name).join('、')],['關聯帳號',`${s.users.filter(u=>u.company===c.id).length} 個帳號`]];}
    if(kind==='entitlement'){const e=s.entitlements.find(e=>e.id===m.id);target=`${companyOf(s,e.company).short} / ${productOf(s,e.product).name}`;before=e.enabled?'產品使用權未暫停':'產品使用權已暫停';after=e.enabled?'只暫停此產品，其他產品不受影響':'解除此產品暫停，仍需期限有效';title=e.enabled?'暫停單一產品':'恢復單一產品';items=[['操作層級','公司底下的單一產品'],['影響帳號',`${members(s,e).length} 個${productOf(s,e.product).name}帳號`],['到期日',e.end]];}
    if(kind==='user'){const u=s.users.find(u=>u.id===m.id);target=`${u.name} / ${productOf(s,u.product).name}`;before=u.status;after=u.status==='停用'?'啟用並占用 1 席':'停用並釋放 1 席';title=u.status==='停用'?'重新啟用帳號':'停用單一帳號';const n=seats(s,entitlementOf(s,u.company,u.product));items=[['公司',companyOf(s,u.company).short],['產品',productOf(s,u.product).name],['名額',`${n.used} / ${n.limit}（含 ${n.invited} 個邀請）`]];if(u.status==='停用'){const allowed=canActivate(s,u);if(!allowed.ok)blocked=allowed.reason;}}
    if(kind==='product'){const p=productOf(s,m.id);target=p.name;before=p.enabled?'產品總開關開啟':'產品總開關關閉';after=p.enabled?'全域停用，所有公司帳號不可使用此產品':'全域開啟，仍需各公司使用權有效';title=p.enabled?'關閉產品總開關':'開啟產品總開關';items=[['操作層級','全域產品'],['影響公司',`${s.entitlements.filter(e=>e.product===p.id).length} 間`],['關聯功能',`${s.features.filter(f=>f.product===p.id).length} 項`]];}
    if(kind==='feature'){const f=s.features.find(f=>f.id===m.id);target=`${productOf(s,f.product).name} / ${f.name}`;before=f.enabled?'功能總開關開啟':'功能總開關關閉';after=f.enabled?'停用此功能，其他功能不受影響':'開啟此功能，仍遵守客戶開放範圍';title=f.enabled?'關閉單一功能':'開啟單一功能';items=[['操作層級','全域功能'],['開放範圍',f.scope],['影響公司',`${s.entitlements.filter(e=>e.product===f.product&&(f.scope==='全部客戶'||f.clients.includes(e.company))).length} 間`]];}
    subtitle=target;body=impact(items)+diff(before,after)+(blocked?note(blocked,'bad'):reason(d.reason)+(kind==='product'||kind==='feature'?field('預計恢復時間（選填）','recovery',d.recovery||'','datetime-local'):'')+`<label class="checkbox"><input name="notify" type="checkbox" ${d.notify===false?'':'checked'}>展示通知受影響對象</label>`+confirmCheck());footer=blocked?btn('知道了','closeModal','','primary'):btn('確認並查看結果','submitSensitive','','danger');
  }
  if(m.type==='term'){const e=s.entitlements.find(e=>e.id===m.id);title='修改產品使用期限';subtitle=`${companyOf(s,e.company).short} / ${productOf(s,e.product).name}`;body=impact([['方案',s.plans.find(p=>p.id===e.plan).name],['目前到期日',e.end],['目前使用狀態',serviceStatus(s,e).label]])+field('新的到期日','end',d.end||e.end,'date','required')+reason(d.reason)+note('此操作只修改所選產品期限，不解除公司、產品或帳號的暫停狀態。')+confirmCheck();footer=btn('確認期限調整','submitTerm','','primary');}
  if(m.type==='access'){const f=s.features.find(f=>f.id===m.id);const a=featureAccess(s,m.company,f);title='功能使用判斷';subtitle=`${companyOf(s,m.company).short} / ${productOf(s,f.product).name} / ${f.name}`;body=`<div class="access-verdict">${status(a.label,a.tone)}<p>${a.reason}</p></div><div class="access-checks">${a.checks.map(c=>`<div><b>${c.name}</b>${status(c.ok?'符合':'阻擋',c.ok?'ok':'bad')}<p>${esc(c.detail)}</p></div>`).join('')}</div>`+note('額外開啟權限的優先序尚待確認。此展示只支援系統預設與強制關閉。')+select('客戶權限設定','mode',['系統預設','強制關閉'],d.mode||a.mode)+reason(d.reason);footer=btn('展示權限調整結果','submitAccess','','primary');}
  if(m.type==='feature'){const f=s.features.find(f=>f.id===m.id)||{product:m.product,name:'',code:'',scope:'僅內部測試',clients:[],version:'v0.1.0'};title=m.id?'功能設定':'新增產品功能';subtitle=`${productOf(s,f.product).name} / ${f.name||'綁定此產品的新功能'}`;const scope=d.scope||f.scope;body=field('功能名稱','name',d.name||f.name,'text','required')+field('功能代碼','code',d.code||f.code,'text','required')+select('開放範圍','scope',['全部客戶','指定客戶','僅內部測試'],scope)+(scope==='指定客戶'?`<fieldset><legend>指定客戶公司</legend>${s.companies.filter(c=>entitlementOf(s,c.id,f.product)).map(c=>`<label class="checkbox"><input name="clients" type="checkbox" value="${c.id}" ${(d.clients||f.clients).includes(c.id)?'checked':''}>${c.short}</label>`).join('')}</fieldset>`:'')+field('版本','version',d.version||f.version)+note('總開關由清單的確認操作管理，這裡只設定功能資料與開放範圍。')+reason(d.reason);footer=btn('查看設定結果','submitFeature','','primary');}
  if(m.type==='quota'){const q=s.quotas.find(q=>q.id===m.id);title='調整使用額度';subtitle=`${companyOf(s,q.company).short} / ${productOf(s,q.product).name} / ${q.name}`;body=impact([['目前用量',`${q.used} / ${q.total} ${q.unit}`],['重置日',q.reset]])+field('調整後總額度','total',d.total??q.total,'number',`required min="${q.used}"`)+field('臨時額度結束日（選填）','expiry',d.expiry||'','date')+reason(d.reason)+note('展示額度調整前後差異；不代表實際計量或扣抵已執行。')+confirmCheck();footer=btn('查看調整結果','submitQuota','','primary');}
  if(m.type==='notification'){const n=s.notifications.find(n=>n.id===m.id)||{name:'新的通知',company:'c1',product:'e2b',channel:'Email',status:'草稿',content:'',time:'2026-10-06T09:00'};title='通知內容與階段';subtitle='草稿、待發送與結果可切換查看；不會真的寄送。';body=select('展示階段','stage',['草稿','待發送','已發送','發送失敗','已取消'],d.stage||n.status)+field('主題','name',d.name??n.name,'text','required')+select('通知對象','company',[...s.companies.map(c=>[c.id,c.short]),['all','所有該產品客戶'],['all-brand','所有採用澄藍樣式的公司']],d.company||n.company)+select('關聯產品','product',s.products.map(p=>[p.id,p.name]),d.product||n.product)+select('管道','channel',['Email','站內通知','Email／站內通知'],d.channel||n.channel)+`<label class="field"><span>通知內容</span><textarea name="content" required>${esc(d.content??n.content)}</textarea></label>`+field('預定時間','time',d.time||(n.time.includes(' ')?n.time.replace(' ','T'):n.time.includes('T')?n.time:''),'datetime-local')+((d.stage||n.status)==='發送失敗'?note(n.error||'發送失敗示意：收件服務暫時無法使用。','bad'):'');footer=btn('儲存展示內容','submitNotification','','primary');}
  if(m.type==='log'){const l=s.logs.find(l=>l.id===m.id);title='操作紀錄詳情';subtitle=`${l.action} / ${l.target}`;body=impact([['時間',l.time],['操作人',l.actor],['模組',l.module],['影響對象',l.target]])+diff(esc(l.before),esc(l.after))+section('操作原因','',`<p class="body-text">${esc(l.reason)}</p>`);footer=btn('關閉','closeModal','','primary');}
  if(m.type==='userInfo'){const u=s.users.find(u=>u.id===m.id);title='邀請狀態';subtitle=u.email;body=impact([['公司',companyOf(s,u.company).short],['所屬產品',productOf(s,u.product).name],['狀態','等待接受邀請'],['名額','已占用 1 席']])+note('此邀請由對應產品後台建立。邀請中占用名額；邀請逾期與撤回政策仍待確認。');footer=btn('關閉','closeModal','','primary');}
  if(['assetPublish','assetRollback','assetRetire'].includes(m.type)){const a=assetOf(s,m.id)||m.asset;const brand=m.asset?m.kind==='brand':assetKind(s,a.id)==='brand';const sites=affectedSites(s,a.id);drawer=false;wide=true;title=m.type==='assetRetire'?'資產下架情境':m.type==='assetRollback'?'歷史版本回復確認':brand?'品牌樣式全域更新':'內容版型發布確認';subtitle=a.name;body=impact([['資產類型',brand?'品牌樣式':'內容版型'],['目前版本',a.version||'新資產'],['受影響網站',`${sites.length} 個`]])+(m.type==='assetRetire'?select('下架處置（展示提案）','retire',['停止新客戶選用，既有網站保留','停止新客戶選用，通知既有客戶更換','全面停止使用'],d.retire||'停止新客戶選用，既有網站保留'):diff(a.version||'尚未發布',m.version||'新版本'))+`<div class="affected-mini">${sites.map(w=>`<div><b>${w.name}</b><span>${w.domain}</span></div>`).join('')||'<p>新資產尚無採用網站。</p>'}</div>`+note(brand?'更新會影響所有採用此品牌樣式的網站，全部一起更新。':'內容版型的更新、內容保留與全面停用政策尚待確認；此操作僅展示結果。',brand?'warn':'info')+reason(d.reason)+confirmCheck();footer=btn('確認並查看結果','submitAsset','','primary');}
  if(m.type==='preview'){const w=s.websites.find(w=>w.id===m.id);const a=m.asset?assetOf(s,m.asset):null;const b=w?s.brands.find(b=>b.id===w.brand):a&&assetKind(s,a.id)==='brand'?a:s.brands[0];const block=a&&assetKind(s,a.id)==='block'?a:null;title=w?w.name:`${a?.name||'網站'}預覽`;subtitle=m.version?`歷史版本 ${m.version} · 視覺為共用示意，非真實版本快照`:'網站視覺示意，非客戶實際公開網站';drawer=false;wide=true;body=`<div class="dialog-preview"><iframe title="網站預覽示意" sandbox srcdoc="${esc(sitePreview(b,block))}"></iframe></div>`;footer=btn('關閉預覽','closeModal','','primary');}
  if(m.type==='staff'){const u=s.staff.find(u=>u.id===m.id);title='內部帳號與權限';subtitle=u.email;body=field('姓名','name',d.name||u.name,'text','required')+field('職務','role',d.role||u.role)+select('管理範圍','scope',['全系統','E2B','官網方案'],d.scope||u.scope)+`<fieldset><legend>動作權限（展示提案）</legend>${['檢視','編輯','發布','停用','系統管理'].map(x=>`<label class="checkbox"><input name="actions" type="checkbox" value="${x}" ${(d.actions||u.actions).includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset>`+reason(d.reason)+note('實際權限矩陣尚待確認；此頁不執行真實授權。');footer=btn('查看權限設定','submitStaff','','primary');}
  if(m.type==='releaseNew'){title='建立發布項目';subtitle='建立可查看各階段的展示紀錄。';body=field('發布標題','name',d.name||'','text','required')+select('所屬產品','product',s.products.map(p=>[p.id,p.name]),d.product||'e2b')+select('發布類型','releaseType',['產品版本','功能發布','品牌樣式','內容版型'],d.releaseType||'產品版本')+field('版本號','version',d.version||'v1.0.0','text','required')+select('開放範圍','scope',['全部客戶','指定客戶','僅內部測試'],d.scope||'全部客戶')+(d.scope==='指定客戶'?`<fieldset><legend>指定客戶公司</legend>${s.companies.filter(c=>entitlementOf(s,c.id,d.product||'e2b')).map(c=>`<label class="checkbox"><input name="clients" type="checkbox" value="${c.id}" ${(d.clients||[]).includes(c.id)?'checked':''}>${c.short}</label>`).join('')}</fieldset>`:'')+field('預定時間','time',d.time||'2026-10-06T10:00','datetime-local')+`<label class="field"><span>發布說明</span><textarea name="description" required>${esc(d.description||'')}</textarea></label>`+note('品牌樣式的正式發布請從品牌樣式詳情操作，以確認全部採用網站的影響。');footer=btn('建立展示草稿','submitRelease','','primary');}
  if(m.type==='setting'){title=m.label;subtitle='展示設定';body=select('設定值','value',m.label==='閒置登出'?['15 分鐘','30 分鐘','60 分鐘']:m.label==='稽核保留'?['180 天','365 天','730 天']:['已啟用','未啟用'],d.value||'')+note('此設定不連接真實驗證或系統配置。');footer=btn('查看設定結果','submitSetting','','primary');}
  if(m.type==='reset'){drawer=false;title='重置展示資料';subtitle='回到預設的客戶、名額與各階段情境。';body=note('本次畫面上的修改會清除，需求討論文件與檔案不受影響。','warn');footer=btn('重置展示','submitReset','','primary');}
  if(m.type==='result'){drawer=false;title='展示結果';subtitle=m.subtitle||'已呈現操作後的狀態';body=note(esc(m.message),'success')+(m.before!==undefined?diff(esc(m.before),esc(m.after)):'')+note('結果只保留在本次展示；重新整理後回到預設情境。');footer=btn('完成','closeModal','','primary');}
  return {title,subtitle,body,footer,drawer,wide};
}
export function renderDialog(s,v) {const d=dialogBody(s,v);if(!d)return '';return `<div class="overlay ${d.drawer?'drawer-overlay':''}"><section class="dialog ${d.drawer?'drawer':''} ${d.wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialogTitle" tabindex="-1"><header class="dialog-header"><div><span class="eyebrow">${d.drawer?'DETAIL / 設定與詳情':'CONFIRMATION / 情境確認'}</span><h2 id="dialogTitle">${d.title}</h2><p>${esc(d.subtitle)}</p></div><button class="close-button" data-action="closeModal" aria-label="關閉視窗">×</button></header><form id="dialogForm"><div class="dialog-body">${d.body}<p id="formError" role="alert" class="form-error" hidden></p></div><footer class="dialog-footer">${btn('取消','closeModal','','ghost')}${d.footer}</footer></form></section></div>`;}
