import { DEMO_DATE } from './data.js';
import { daysUntil,companyOf,productOf,entitlementOf,members,seats,serviceStatus,accountAccess,featureAccess } from './model.js';
import { esc,status,btn,link,section,field,select,note,progress,tabs } from './ui.js';
export const navigation = [
  ['工作台',[['overview','營運總覽'],['companies','客戶公司'],['users','產品用戶']]],
  ['產品與官網',[['products','產品與功能'],['plans','方案與帳號名額'],['brands','品牌樣式'],['blocks','內容版型'],['releases','版本與發布']]],
  ['營運管理',[['quotas','使用量與額度'],['notifications','通知中心'],['logs','操作紀錄']]],
  ['系統',[['staff','內部帳號'],['settings','系統設定'],['guide','展示與需求說明']]]
];
export const titles = {
  overview:['營運總覽','掌握服務狀態，從需要處理的事項開始。'],
  companies:['客戶公司','管理實際使用服務的公司與產品使用權。'],
  users:['產品用戶','E2B 與官網分別邀請、分別管理帳號。'],
  products:['產品與功能','控制產品運行、功能狀態與客戶開放範圍。'],
  plans:['方案與帳號名額','以公司為單位，分產品查看名額與使用情況。'],
  brands:['品牌樣式','管理網站整體視覺；發布後所有採用網站同步更新。'],
  blocks:['內容版型','管理內容結構、可編輯欄位與頁面呈現方式。'],
  releases:['版本與發布','從檢查、測試到發布，清楚呈現每個階段。'],
  quotas:['使用量與額度','分產品、分功能查看用量與調整情境。'],
  notifications:['通知中心','查看草稿、排程與各種發送結果。'],
  logs:['操作紀錄','保留操作範圍、變更前後內容與原因。'],
  staff:['內部帳號','公司內部管理人員的操作範圍與權限。'],
  settings:['系統設定','服務規則與管理環境的展示設定。'],
  guide:['展示與需求說明','已確認的規則、展示情境與待討論事項。']
};
export function table(v,key,columns,rows,options={}) {
  let list=rows.filter(r=>!v.query||String(r.search||r.cells.join(' ')).toLowerCase().includes(v.query.toLowerCase()));
  if(v.sort==='name') list.sort((a,b)=>String(a.search||'').localeCompare(String(b.search||''),'zh-Hant'));
  const page=v.tablePages[key]||1,size=options.size||8,total=list.length,pages=Math.max(1,Math.ceil(total/size)),current=Math.min(page,pages);
  const shown=list.slice((current-1)*size,current*size);
  return `<div class="data-table"><div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${shown.length?shown.map(r=>`<tr>${r.cells.map((c,i)=>`<td ${i===r.cells.length-1?'class="actions-cell"':''}>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}"><div class="empty"><strong>沒有符合條件的資料</strong><span>試著調整搜尋或篩選條件。</span></div></td></tr>`}</tbody></table></div>${options.footer===false?'':`<div class="table-footer"><span>${total?`${(current-1)*size+1}–${Math.min(current*size,total)}`:'0'} / ${total} 筆</span><div>${btn('上一頁','tablePage',`data-key="${key}" data-value="${current-1}" ${current<=1?'disabled':''}`,'small ghost')}<span>${current} / ${pages}</span>${btn('下一頁','tablePage',`data-key="${key}" data-value="${current+1}" ${current>=pages?'disabled':''}`,'small ghost')}</div></div>`}</div>`;
}
export function toolbar(v,options=[],extra='') {return `<div class="toolbar"><div class="toolbar-left">${options.length?`<select aria-label="狀態篩選" data-view="filter">${['全部',...options].map(x=>`<option ${v.filter===x?'selected':''}>${x}</option>`).join('')}</select>`:''}<select aria-label="排序" data-view="sort"><option value="default" ${v.sort==='default'?'selected':''}>預設排序</option><option value="name" ${v.sort==='name'?'selected':''}>名稱排序</option></select>${extra}</div><label class="inline-search"><span>搜尋</span><input id="pageSearch" value="${esc(v.query)}" placeholder="搜尋目前清單" aria-label="搜尋目前清單"></label></div>`;}
function companyCell(c) {return `<div class="entity"><span class="monogram">${esc(c.short.slice(0,1))}</span><div>${link(c.name,'company',`data-id="${c.id}"`)}<small class="mono">${c.code}</small></div></div>`;}
function productChip(s,id) {return `<span class="product-label ${id}">${productOf(s,id)?.name||id}</span>`;}
function countStrip(items) {return `<div class="metric-strip">${items.map(([label,value,sub])=>`<div><span>${label}</span><strong>${value}</strong><small>${sub||''}</small></div>`).join('')}</div>`;}
export function companyPage(s,v) {
  let rows=s.companies.filter(c=>v.filter==='全部'||(v.filter==='公司已暫停'&&!c.enabled)||(v.filter==='使用中'&&c.enabled)||(v.filter==='含到期產品'&&s.entitlements.some(e=>e.company===c.id&&daysUntil(e.end)<0)));
  if(v.productFilter!=='all')rows=rows.filter(c=>entitlementOf(s,c.id,v.productFilter));
  return toolbar(v,['使用中','含到期產品','公司已暫停'],productSelect(v))+table(v,'companies',['公司／代碼','產品使用權','帳號名額','公司狀態','內部負責人','操作'],rows.map(c=>{const es=s.entitlements.filter(e=>e.company===c.id);return {search:`${c.name} ${c.code} ${c.owner}`,cells:[companyCell(c),`<div class="cell-stack">${es.map(e=>`<span>${productChip(s,e.product)} ${status(serviceStatus(s,e).label)}</span>`).join('')}</div>`,`<div class="cell-stack">${es.map(e=>{const n=seats(s,e);return `<span><small>${productOf(s,e.product).name}</small> <b class="numeric">${n.used} / ${n.limit}</b>${n.used===n.limit?'<em class="muted">額滿</em>':''}</span>`;}).join('')}</div>`,status(c.enabled?'正常':'公司已暫停'),c.owner,btn('查看公司','openCompany',`data-id="${c.id}"`,'small ghost')]};}));
}
function productSelect(v) {return `<select aria-label="產品篩選" data-view="productFilter"><option value="all" ${v.productFilter==='all'?'selected':''}>全部產品</option><option value="e2b" ${v.productFilter==='e2b'?'selected':''}>E2B</option><option value="web" ${v.productFilter==='web'?'selected':''}>官網方案</option></select>`;}
export function overview(s,v) {
  const exp=s.entitlements.filter(e=>daysUntil(e.end)<0);const soon=s.entitlements.filter(e=>daysUntil(e.end)>=0&&daysUntil(e.end)<=30);const active=s.entitlements.filter(e=>['使用中','即將到期'].includes(serviceStatus(s,e).label));const invite=s.users.filter(u=>u.status==='邀請中');
  const attention=[];
  for(const e of exp.slice(0,2))attention.push(['到期',`${companyOf(s,e.company).short}的${productOf(s,e.product).name}使用權已到期`,'只影響此產品底下帳號，另一產品依自身使用權判斷。','company',e.company,'bad',e.product]);
  for(const e of s.entitlements.filter(e=>seats(s,e).remaining===0).slice(0,1)){const n=seats(s,e);attention.push(['名額',`${companyOf(s,e.company).short} ${productOf(s,e.product).name}名額已滿`,`${n.active} 個啟用 + ${n.invited} 個邀請；重新啟用前需釋出名額。`,'company',e.company,'warn',e.product]);}
  const upcoming=s.releases.find(r=>r.status==='待發布');if(upcoming)attention.push(['發布',upcoming.name,'查看發布階段與影響對象。','release',upcoming.id,'info']);
  const failed=s.blocks.find(a=>a.status==='檢查失敗');if(failed)attention.push(['檢查',`${failed.name}檢查失敗`,'查看明細，修正後再重新檢查。','asset',failed.id,'bad']);
  return `<div class="overview-lead"><div><span class="eyebrow">MONDAY / ${DEMO_DATE.replaceAll('-','.')}</span><h2>每一項服務，都有清楚的狀態。</h2><p>公司、產品與用戶分層管理，從異常到影響範圍一眼看懂。</p></div><div class="live-summary">${status('系統展示環境')}<span>資料基準日 ${DEMO_DATE}</span></div></div>`+countStrip([['實際客戶公司',s.companies.length,'含暫停與到期服務'],['有效產品使用權',active.length,`共 ${s.entitlements.length} 筆使用權`],['到期／即將到期',`${exp.length} / ${soon.length}`,'產品分別計算'],['待接受邀請',invite.length,'已計入方案名額']])+`<div class="overview-columns"><div>${section('需要關注','依服務影響排列，直接進入對應情境。',`<div class="attention-list">${attention.map(([tag,title,desc,page,id,tone,product],i)=>`<button data-page="${page}" data-id="${id}" data-product="${product||''}" class="attention-row"><span class="row-number">0${i+1}</span><div><span class="tag ${tone}">${tag}</span><strong>${title}</strong><p>${desc}</p></div><span class="arrow">↗</span></button>`).join('')}</div>`)}</div><aside>${section('產品運行','全域開關影響所有使用客戶。',s.products.map(p=>`<div class="product-run"><div class="product-run-head"><b>${p.name}</b>${status(p.enabled?'運行正常':'產品全域停用')}</div><p>${p.description}</p><div class="run-meta"><span>${p.version}</span><span>${s.entitlements.filter(e=>e.product===p.id).length} 間公司</span><span>${s.features.filter(f=>f.product===p.id).length} 項功能</span></div>${link('管理產品 →','product',`data-id="${p.id}"`)}</div>`).join(''))}</aside></div>`+section('近期操作','每次異動都能回到公司、產品或用戶。',table({...v,query:''},'overviewLogs',['時間','操作人','操作','影響對象'],s.logs.slice(0,4).map(l=>({cells:[`<span class="mono">${l.time}</span>`,l.actor,l.action,l.target]})),{footer:false}),link('所有操作紀錄 →','logs'));
}
export function companyDetail(s,v) {
  const c=companyOf(s,v.id)||s.companies[0];const es=s.entitlements.filter(e=>e.company===c.id);if(!es.some(e=>e.product===v.companyProduct))v.companyProduct=es[0]?.product||'e2b';const e=es.find(e=>e.product===v.companyProduct);
  const plan=s.plans.find(p=>p.id===e?.plan);const n=e?seats(s,e):null;const st=e?serviceStatus(s,e):null;
  return `<div class="detail-identity"><div class="entity large"><span class="monogram">${c.short[0]}</span><div><span class="eyebrow">${c.code} / ${c.industry}</span><h2>${c.name}</h2><p>${c.contact} · ${c.email} <span class="divider">|</span> 負責人 ${c.owner}</p></div></div><div class="identity-actions">${status(c.enabled?'公司正常':'公司已暫停')}${btn(c.enabled?'暫停整間公司':'恢復整間公司','sensitive',`data-kind="company" data-id="${c.id}"`,c.enabled?'danger-outline':'secondary')}</div></div>`+tabs(es.map(e=>[e.product,productOf(s,e.product).name]),v.companyProduct,'companyProduct')+`<div class="service-summary"><div><span class="eyebrow">${productOf(s,e.product).billing}</span><h3>${plan.name}</h3><p>服務期間 ${e.start} — ${e.end}</p><small>方案名稱與席次為展示資料</small></div><div><span>使用權狀態</span>${status(st.label,st.tone)}<small>${st.reason}</small></div><div><span>帳號名額</span><strong>${n.used}<small> / ${n.limit}</small></strong><p>${n.active} 啟用 · ${n.invited} 邀請中 · ${n.inactive} 停用</p>${progress(n.used,n.limit)}</div><div class="service-actions">${btn('修改使用期限','editTerm',`data-id="${e.id}"`)}${btn(e.enabled?'暫停此產品':'恢復此產品','sensitive',`data-kind="entitlement" data-id="${e.id}"`,'ghost')}</div></div>`+tabs([['users','產品用戶',members(s,e).length],['features','功能權限'],['usage','使用量'],...(e.product==='web'?[['website','官網設定']]:[]),['history','異動紀錄']],v.detailTab,'detailTab')+companyTab(s,v,c,e);
}
function companyTab(s,v,c,e) {
  if(v.detailTab==='features')return note('展示「系統預設」與「強制關閉」。額外開啟的優先序仍待確認；畫面不將它當成已定案規則。')+table(v,'companyFeatures',['功能／代碼','開放範圍','客戶權限','最終狀態','原因','操作'],s.features.filter(f=>f.product===e.product).map(f=>{const a=featureAccess(s,c.id,f);return {search:f.name,cells:[`<b>${f.name}</b><small class="mono">${f.code}</small>`,f.scope,a.mode,status(a.label,a.tone),`<span class="reason">${esc(a.reason)}</span>`,btn('查看判斷','inspectAccess',`data-company="${c.id}" data-id="${f.id}"`,'small ghost')]};}));
  if(v.detailTab==='usage')return quotaTable(s,v,s.quotas.filter(q=>q.company===c.id&&q.product===e.product));
  if(v.detailTab==='website'){const w=s.websites.find(w=>w.company===c.id);if(!w)return note('此公司尚無展示網站資料。');const b=s.brands.find(b=>b.id===w.brand);return `<div class="website-summary"><div><span class="eyebrow">客戶網站</span><h3>${w.name}</h3><p class="mono">${w.domain}</p></div>${btn('查看網站示意','previewSite',`data-id="${w.id}"`)}</div>`+note('產品到期限制官網後台帳號。公開網站是否下線尚未定案，此畫面不推論網站已下線。')+section('品牌樣式','整體品牌視覺。所有採用此樣式的網站會同步更新。',`<div class="asset-inline"><span class="color-swatch" style="background:${b.color}"></span><div><b>${b.name}</b><small>${b.version} · ${b.font}</small></div>${link('管理品牌樣式 →','asset',`data-id="${b.id}"`)}</div>`)+section('使用的內容版型','內容結構與呈現方式，與品牌樣式分開管理。',table(v,'websiteBlocks',['內容版型','版本','呈現方式','操作'],w.blocks.map(id=>{const bl=s.blocks.find(b=>b.id===id);return {cells:[bl.name,bl.version,bl.layout,link('查看版型','asset',`data-id="${id}"`)]};}),{footer:false}));}
  if(v.detailTab==='history')return logsTable(s,v,s.logs.filter(l=>l.target.includes(c.short)));
  const n=seats(s,e);return `<div class="section-heading compact"><div><h2>${productOf(s,e.product).name} 用戶</h2><p>邀請從該產品後台發起；總控台查看及管理帳號狀態。</p></div><span class="seat-caption">已占用 <b>${n.used} / ${n.limit}</b>${n.remaining===0?' · 名額已滿':''}</span></div>`+note('啟用與邀請中都占名額；停用不占名額。重新啟用需再次檢查上限。')+usersTable(s,v,members(s,e),false);
}
export function usersPage(s,v) {let rows=s.users.filter(u=>v.productFilter==='all'||u.product===v.productFilter);rows=rows.filter(u=>v.filter==='全部'||u.status===v.filter||(v.filter==='不可使用'&&accountAccess(s,u).label==='不可使用'));return toolbar(v,['啟用','邀請中','停用','不可使用'],productSelect(v))+usersTable(s,v,rows,true);}
function usersTable(s,v,list,global) {return table(v,global?'users':'companyUsers',[global?'用戶／公司':'用戶','產品','帳號狀態','實際使用','名額','最後登入','操作'],list.map(u=>{const a=accountAccess(s,u);return {search:`${u.name} ${u.email} ${companyOf(s,u.company).name}`,cells:[`<div class="user-cell"><span class="avatar">${u.name[0]}</span><div><b>${u.name}</b><small>${u.email}</small>${global?`<small>${link(companyOf(s,u.company).short,'company',`data-id="${u.company}"`)}</small>`:''}</div></div>`,productChip(s,u.product),status(u.status),`<div>${status(a.label,a.tone)}<small class="reason">${a.reason}</small></div>`,u.status==='停用'?'<span class="muted">不占名額</span>':'1 席',`<span class="mono">${u.lastLogin}</span>`,u.status==='邀請中'?btn('查看邀請','userInfo',`data-id="${u.id}"`,'small ghost'):btn(u.status==='停用'?'重新啟用':'停用','sensitive',`data-kind="user" data-id="${u.id}"`,'small ghost')]};}));}
export function productsPage(s,v) {return s.products.map(p=>{const es=s.entitlements.filter(e=>e.product===p.id);return `<section class="product-sheet"><div class="product-sheet-head"><div><span class="eyebrow">${p.code} / ${p.billing}</span><h2>${p.name}</h2><p>${p.description}</p></div><div>${status(p.enabled?'運行正常':'產品全域停用')}${btn(p.enabled?'關閉總開關':'開啟總開關','sensitive',`data-kind="product" data-id="${p.id}"`,'ghost')}${btn('管理產品 →','openProduct',`data-id="${p.id}"`,'primary')}</div></div><div class="product-numbers"><span><b>${es.length}</b>使用公司</span><span><b>${s.features.filter(f=>f.product===p.id).length}</b>功能</span><span><b>${s.users.filter(u=>u.product===p.id&&u.status!=='停用').length}</b>占用名額</span><span><b>${p.version}</b>目前版本</span><span>負責人 <b>${p.owner}</b></span></div></section>`;}).join('')+note('產品總開關屬全域操作；公司詳情中的產品暫停只影響該公司。');}
export function productDetail(s,v) {const p=productOf(s,v.id)||s.products[0];return `<div class="detail-identity"><div><span class="eyebrow">${p.code} / ${p.billing}</span><h2>${p.name}</h2><p>${p.description} · ${p.version} · ${p.owner}</p></div><div class="identity-actions">${status(p.enabled?'運行正常':'產品全域停用')}${btn(p.enabled?'關閉產品總開關':'開啟產品總開關','sensitive',`data-kind="product" data-id="${p.id}"`,'danger-outline')}</div></div>`+tabs([['features','功能管理'],['clients','使用客戶'],['releases','版本紀錄']],v.productTab,'productTab')+(v.productTab==='clients'?table(v,'productClients',['公司','方案','使用狀態','到期日','操作'],s.entitlements.filter(e=>e.product===p.id).map(e=>({search:companyOf(s,e.company).name,cells:[companyCell(companyOf(s,e.company)),s.plans.find(pl=>pl.id===e.plan).name,status(serviceStatus(s,e).label),e.end,link('管理公司使用權','company',`data-id="${e.company}" data-product="${p.id}"`)]}))):v.productTab==='releases'?releaseTable(s,v,s.releases.filter(r=>r.product===p.id)):toolbar(v,['已釋出','指定客戶測試','內部測試','維護中'])+table(v,'features',['功能／代碼','版本','狀態','開放範圍','功能開關','操作'],s.features.filter(f=>f.product===p.id&&(v.filter==='全部'||f.status===v.filter)).map(f=>({search:`${f.name} ${f.code}`,cells:[`<b>${f.name}</b><small class="mono">${f.code}</small>`,f.version,status(f.status),f.scope,`<button class="switch ${f.enabled?'on':''}" role="switch" aria-checked="${f.enabled}" aria-label="${f.name}功能總開關" data-action="sensitive" data-kind="feature" data-id="${f.id}"><span></span></button>`,btn('設定','featureSettings',`data-id="${f.id}"`,'small ghost')]})),{size:11}));}
export function plansPage(s,v) {return note('方案名稱、席次與額度為展示配置；E2B 以公司訂閱，官網依公司合約管理。')+section('名額計算規則','新增與重新啟用都需檢查上限。',`<div class="rule-equation"><span>啟用帳號</span><b>＋</b><span>邀請中帳號</span><b>＝</b><strong>已占用名額</strong><small>停用帳號不計入</small></div>`)+toolbar(v,[],productSelect(v))+table(v,'planSeats',['公司','產品／方案','啟用','邀請中','停用','已占用／上限','操作'],s.entitlements.filter(e=>v.productFilter==='all'||e.product===v.productFilter).map(e=>{const n=seats(s,e);return {search:companyOf(s,e.company).name,cells:[companyCell(companyOf(s,e.company)),`${productChip(s,e.product)}<small>${s.plans.find(p=>p.id===e.plan).name}</small>`,n.active,n.invited,`<span class="muted">${n.inactive}</span>`,`<div class="quota-number"><b>${n.used} / ${n.limit}</b>${n.remaining===0?status('名額已滿','warn'):`<small>剩餘 ${n.remaining} 席</small>`}${progress(n.used,n.limit)}</div>`,link('查看產品用戶','company',`data-id="${e.company}" data-product="${e.product}"`)]};}));}
function quotaTable(s,v,list) {return table(v,'quotas',['公司／產品','額度類型','已用／總額度','使用比例','重置日','狀態','操作'],list.map(q=>{const ratio=q.used/q.total;return {search:`${companyOf(s,q.company).name} ${q.name}`,cells:[`${link(companyOf(s,q.company).short,'company',`data-id="${q.company}"`)}<small>${productOf(s,q.product).name}</small>`,q.name,`<span class="numeric">${q.used} / ${q.total}</span> ${q.unit}`,`<div class="quota-number"><b>${Math.round(ratio*100)}%</b>${progress(q.used,q.total)}</div>`,q.reset,status(ratio>=1?'已用完':ratio>=.85?'接近上限':'正常',ratio>=1?'bad':ratio>=.85?'warn':'ok'),btn('調整額度','quotaEdit',`data-id="${q.id}"`,'small ghost')]};}));}
function releaseTable(s,v,list) {return table(v,'releases',['發布項目','產品／類型','版本','開放範圍','狀態','發布時間','操作'],list.map(r=>({search:`${r.name} ${r.type}`,cells:[`<b>${r.name}</b><small>${r.owner}</small>`,`${productChip(s,r.product)}<small>${r.type}</small>`,`<span class="mono">${r.version}</span>`,r.scope,status(r.status),`<span class="mono">${r.time}</span>`,link('查看階段','release',`data-id="${r.id}"`)]})));}
function notificationsPage(s,v) {return toolbar(v,['草稿','待發送','已發送','發送失敗','已取消'])+table(v,'notifications',['通知主題','對象','管道','狀態','預定／發送時間','操作'],s.notifications.filter(n=>v.filter==='全部'||n.status===v.filter).map(n=>({search:n.name,cells:[`<b>${n.name}</b><small>${productOf(s,n.product).name}</small>`,companyOf(s,n.company)?.short||(n.company==='all-brand'?'所有採用澄藍樣式的公司':'所有該產品客戶'),n.channel,status(n.status),`<span class="mono">${n.time}</span>`,btn('查看通知','notification',`data-id="${n.id}"`,'small ghost')]})));}
function logsTable(s,v,list) {return table(v,'logs',['操作時間','操作人','模組','操作內容','影響對象','操作'],list.map(l=>({search:`${l.actor} ${l.action} ${l.target} ${l.reason}`,cells:[`<span class="mono">${l.time}</span>`,l.actor,l.module,l.action,l.target,btn('查看差異','log',`data-id="${l.id}"`,'small ghost')]})));}
function staffPage(s,v) {return note('內部管理帳號與客戶產品帳號分開管理。此頁的動作權限為展示提案，實際職務權限仍需確認。')+table(v,'staff',['管理人員','職務','管理範圍','操作權限','狀態','操作'],s.staff.map(u=>({search:`${u.name} ${u.role}`,cells:[`<b>${u.name}</b><small>${u.email}</small>`,u.role,u.scope,`<div class="permission-tags">${u.actions.map(a=>`<span>${a}</span>`).join('')}</div>`,status(u.status),btn('設定權限','staff',`data-id="${u.id}"`,'small ghost')]})));}
function settingsPage(s,v) {return tabs([['rules','服務規則'],['security','管理安全']],v.settingsTab,'settingsTab')+(v.settingsTab==='security'?section('管理環境','安全項目是畫面提案，尚未連接真實驗證。',`<div class="settings-rows">${[['雙因素驗證','內部管理帳號的登入保護','已啟用'],['閒置登出','管理員超過指定時間未操作','30 分鐘'],['稽核保留','服務與權限異動的紀錄','365 天']].map(([a,b,c])=>`<div><div><b>${a}</b><p>${b}</p></div>${btn(c,'setting',`data-label="${a}"`)}</div>`).join('')}</div>`):section('已確認的服務規則','目前討論的規則，作為各頁畫面的共同依據。',`<div class="settings-rows">${[['計費與帳號','以公司計費；E2B 與官網各自邀請帳號。','公司／產品'],['帳號名額','啟用與邀請中占用名額，停用不占。','依方案上限'],['重新啟用','額滿時禁止重新啟用停用帳號。','需檢查名額'],['產品到期','該公司在到期產品底下的全部帳號不可使用。','另一產品不受影響'],['品牌樣式更新','所有採用該樣式的客戶網站同步更新。','全部一起更新']].map(([a,b,c])=>`<div><div><b>${a}</b><p>${b}</p></div><span class="rule-value">${c}</span></div>`).join('')}</div>`));}
function guidePage() {return section('如何查看這份展示','使用各頁情境選擇器與階段頁籤，查看不同結果。',`<ol class="guide-list"><li><b>公司 → 產品 → 用戶</b><p>遠星科技展示 E2B 有效、官網到期；兩個产品的用戶名單各自獨立。</p></li><li><b>名額額滿與重新啟用</b><p>晨港物流展示 2 個啟用 + 1 個邀請 = 3 席額滿，停用帳號無法重新啟用。</p></li><li><b>三種暫停範圍</b><p>公司詳情可暫停整間公司或單一產品，用戶列表可停用單一帳號。</p></li><li><b>官網資產的階段</b><p>品牌樣式與內容版型各自有基本資料、檢查、預覽、測試與發布畫面。</p></li><li><b>操作前後與紀錄</b><p>確認視窗呈現影響、原因與差異；結果可於本次展示切換查看，重新整理即回到預設資料。</p></li></ol>`)+section('尚待討論','不將未確認規則當作正式政策。',`<div class="settings-rows">${['官網到期後，公開網站的服務處置。','客戶額外開啟權限的優先序與期限。','內容版型更新與更換時，既有內容保留方式。','方案降級、人工調整名額與邀請到期的處理方式。','實際方案名稱、價格、功能與額度配置。'].map(t=>`<div><span>${t}</span>${status('待確認')}</div>`).join('')}</div>`);}
export function basicPage(s,v) {
  if(v.page==='overview')return overview(s,v);
  if(v.page==='companies')return companyPage(s,v);
  if(v.page==='company')return companyDetail(s,v);
  if(v.page==='users')return usersPage(s,v);
  if(v.page==='products')return productsPage(s,v);
  if(v.page==='product')return productDetail(s,v);
  if(v.page==='plans')return plansPage(s,v);
  if(v.page==='quotas')return toolbar(v,[],productSelect(v))+quotaTable(s,v,s.quotas.filter(q=>v.productFilter==='all'||q.product===v.productFilter))+note('額度值與限制動作為展示情境，實際各產品的額度配置尚待確認。');
  if(v.page==='releases')return toolbar(v,['草稿','待發布','測試中','已發布','發布失敗','已取消'])+releaseTable(s,v,s.releases.filter(r=>v.filter==='全部'||r.status===v.filter));
  if(v.page==='notifications')return notificationsPage(s,v);
  if(v.page==='logs')return toolbar(v)+logsTable(s,v,s.logs);
  if(v.page==='staff')return staffPage(s,v);
  if(v.page==='settings')return settingsPage(s,v);
  if(v.page==='guide')return guidePage();
  return '';
}
