export function esc(v='') { return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
export function status(label,tone) { const bad=['已到期','停用','公司已暫停','產品已暫停','產品全域停用','不可使用','檢查失敗','發送失敗','已下架']; const warn=['邀請中','等待接受','即將到期','待發布','待發送','待確認']; const info=['測試中','草稿','僅內部測試','指定客戶測試','內部測試']; tone=tone||(bad.includes(label)?'bad':warn.includes(label)?'warn':info.includes(label)?'info':'ok'); return `<span class="status ${tone}"><i></i>${esc(label)}</span>`; }
export function btn(label,action,attrs='',style='secondary') { return `<button class="btn ${style}" data-action="${action}" ${attrs}>${label}</button>`; }
export function link(label,page,attrs='') {return `<button class="text-link" data-page="${page}" ${attrs}>${esc(label)}</button>`;}
export function section(title,description,body,action='') {return `<section class="section"><div class="section-heading"><div><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${action}</div>${body}</section>`;}
export function field(label,key,value,type='text',extra='') { return `<label class="field"><span>${label}</span><input name="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`; }
export function select(label,key,options,value) {return `<label class="field"><span>${label}</span><select name="${key}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;}
export function note(text,tone='info') {return `<div class="notice ${tone}">${text}</div>`;}
export function progress(used,total) {const percent=Math.min(100,Math.round(used/total*100));return `<div class="usage-bar ${percent>=100?'bad':percent>=85?'warn':''}" role="meter" aria-label="使用比例" aria-valuenow="${percent}" aria-valuemin="0" aria-valuemax="100"><span style="width:${percent}%"></span></div>`;}
export function steps(labels,current) {return `<ol class="stepper">${labels.map((l,i)=>`<li class="${i===current?'current':i<current?'complete':''}"><button type="button" data-action="wizardStep" data-step="${i}"><span>${String(i+1).padStart(2,'0')}</span>${l}</button></li>`).join('')}</ol>`;}
export function tabs(items,current,action='tab') {return `<div class="tabs" role="tablist">${items.map(([id,label,count])=>`<button role="tab" aria-selected="${id===current}" class="${id===current?'active':''}" data-action="${action}" data-tab="${id}">${label}${count!==undefined?`<span>${count}</span>`:''}</button>`).join('')}</div>`;}
