import {DEMO_DATE} from './data.js';
import {companyOf,productOf,entitlementOf,seats,serviceStatus,daysUntil} from './model.js';
import {esc,status,btn,link,section,field,select,note,tabs} from './ui.js';
import {table,toolbar} from './screens.js';
import {assetOf,assetKind} from './assets.js';
function restoreReason(d){return `<label class="field"><span>操作原因 <em>必填</em></span><textarea name="reason" required>${esc(d.reason||'')}</textarea></label>`;}
function restoreText(label,name,value=''){return `<label class="field"><span>${label}</span><textarea name="${name}">${esc(value)}</textarea></label>`;}
export function restorePage(s,v){
  if(v.page==='products')return toolbar(v,['已上線','運行正常','維護中','停止服務','已下架','開發中'])+table(v,'products',['產品／代碼','負責人','說明','版本','狀態','功能／使用公司','最近更新','總開關','操作'],s.products.filter(p=>v.filter==='全部'||(p.enabled?p.status:'停止服務')===v.filter).map(p=>({search:p.name+' '+p.code+' '+p.owner,cells:[`<b>${p.name}</b><small class="mono">${p.code}</small>`,p.owner,`<span class="reason">${esc(p.description)}</span>`,p.version,status(p.enabled?p.status:'停止服務'),`${s.features.filter(f=>f.product===p.id).length} 項功能<small>${new Set(s.entitlements.filter(e=>e.product===p.id).map(e=>e.company)).size} 間公司</small>`,p.updated,`<button class="switch ${p.enabled?'on':''}" role="switch" aria-checked="${p.enabled}" aria-label="${p.name}產品總開關" data-action="sensitive" data-kind="product" data-id="${p.id}"><span></span></button>`,btn('管理','openProduct',`data-id="${p.id}"`,'small')+btn('編輯','productEdit',`data-id="${p.id}"`,'small ghost')]})));
  if(v.page==='features')return toolbar(v,['已釋出','維護中','指定客戶測試','內部測試','開發中'],`<select aria-label="產品篩選" data-view="productFilter"><option value="all">全部產品</option>${s.products.map(p=>`<option value="${p.id}" ${v.productFilter===p.id?'selected':''}>${p.name}</option>`).join('')}</select>`)+table(v,'allFeatures',['功能／代碼','所屬產品','版本','狀態','開放範圍／客戶數','負責人／更新','總開關','操作'],s.features.filter(f=>(v.productFilter==='all'||v.productFilter===f.product)&&(v.filter==='全部'||v.filter===f.status)).map(f=>({search:`${f.name} ${f.code}`,cells:[`<b>${esc(f.name)}</b><small class="mono">${f.code}</small>`,productOf(s,f.product).name,f.version,status(f.status),`${f.scope}<small>${s.entitlements.filter(e=>e.product===f.product&&(f.scope==='全部客戶'||(f.scope==='指定客戶'&&f.clients.includes(e.company)))).length} 間開放對象</small>`,`${f.owner}<small>${f.updated||DEMO_DATE}</small>`,`<button class="switch ${f.enabled?'on':''}" role="switch" aria-checked="${f.enabled}" aria-label="${f.name}功能總開關" data-action="sensitive" data-kind="feature" data-id="${f.id}"><span></span></button>`,btn('編輯','featureSettings',`data-id="${f.id}"`,'small ghost')]})));
  if(v.page==='entitlements'){let list=s.entitlements.filter(e=>v.productFilter==='all'||e.product===v.productFilter);list=list.filter(e=>v.filter==='全部'||(v.filter==='試用中'&&e.mode==='試用')||(v.filter==='等待開通'&&e.stage==='等待開通')||(v.filter==='即將到期'&&daysUntil(e.end)>=0&&daysUntil(e.end)<=30)||(v.filter==='已到期'&&daysUntil(e.end)<0)||(v.filter==='暫停／待開通'&&!['使用中','即將到期'].includes(serviceStatus(s,e).label))||serviceStatus(s,e).label===v.filter);return toolbar(v,['使用中','即將到期','已到期','試用中','等待開通','暫停／待開通'],`<select aria-label="產品篩選" data-view="productFilter"><option value="all">全部產品</option>${s.products.map(p=>`<option value="${p.id}" ${v.productFilter===p.id?'selected':''}>${p.name}</option>`).join('')}</select>`)+table(v,'rights',['公司','產品／方案','服務類型','使用期間','狀態／付款','帳號名額','操作'],list.map(e=>{const n=seats(s,e);return {search:companyOf(s,e.company).name,cells:[link(companyOf(s,e.company).short,'company',`data-id="${e.company}" data-product="${e.product}"`),`${productOf(s,e.product).name}<small>${s.plans.find(p=>p.id===e.plan)?.name}</small>`,e.mode==='試用'?status('試用中','info'):e.mode||'正式服務',`${e.start}<small>至 ${e.end}</small>`,`${status(serviceStatus(s,e).label)}<small>${e.payment}</small>`,`${n.used} / ${n.limit}`,`${btn('管理使用權','entitlementEdit',`data-id="${e.id}"`,'small ghost')}${btn('延長期限','extendTerm',`data-id="${e.id}"`,'small ghost')}`]};}));}
  if(v.page==='tasks')return toolbar(v,['待處理','處理中','已處理'])+table(v,'taskQueue',['事項','產品','優先序','負責人','狀態','操作'],s.tasks.filter(t=>v.filter==='全部'||t.state===v.filter).map(t=>({search:`${t.title} ${t.desc}`,cells:[`<b>${t.title}</b><small>${t.desc}</small>`,productOf(s,t.product)?.name||'公司服務',status(t.priority,t.priority==='高'?'bad':'warn'),t.owner,status(t.state),btn('處理','task',`data-id="${t.id}"`,'small ghost')]})));
  return null;
}
export function notificationRules(s,v){return `<div class="settings-rows">${s.notificationRules.map(r=>`<div><div><b>${r.name}</b><p>${r.channel} · ${r.condition}</p></div>${status(r.enabled?'已啟用':'已停用',r.enabled?'ok':'bad')}${btn('設定規則','notificationRule',`data-id="${r.id}"`,'small')}</div>`).join('')}</div>`;}
export function quotaHierarchy(s,v){
 const search=(v.query||'').toLowerCase();
 return `<div class="quota-heading"><h2>產品用量與客戶明細</h2><p>產品 → 客戶公司 → 客戶用戶。公司額度為共用上限，用戶層呈現實際用量，不重複分配公司名額或額度。</p></div>`+toolbar(v)+`<div class="quota-tree">${s.products.map(p=>{const list=s.quotas.filter(q=>q.product===p.id);const companies=[...new Set(s.entitlements.filter(e=>e.product===p.id).map(e=>e.company))].filter(id=>!search||`${companyOf(s,id).name} ${p.name} ${s.users.filter(u=>u.company===id&&u.product===p.id).map(u=>u.name+' '+u.email).join(' ')}`.toLowerCase().includes(search));const expanded=v.quotaExpanded[p.id]||!!search;return `<section class="quota-product"><button class="quota-product-head" data-action="quotaExpand" data-key="${p.id}" aria-expanded="${!!expanded}"><span class="tree-arrow">${expanded?'▾':'▸'}</span><span class="product-emblem">${p.id==='e2b'?'E':'W'}</span><div><b>${p.name}</b><small>${companies.length} 間公司 · ${list.length} 項公司額度</small></div><span>${list.filter(q=>q.used/q.total>=.85).length} 項接近上限</span></button>${expanded?`<div class="quota-companies">${companies.map(id=>{const c=companyOf(s,id),qs=list.filter(q=>q.company===id),key=p.id+'-'+id,open=v.quotaExpanded[key]||!!search,us=s.users.filter(u=>u.company===id&&u.product===p.id),e=entitlementOf(s,id,p.id);return `<section class="quota-company"><button class="quota-company-head" data-action="quotaExpand" data-key="${key}" aria-expanded="${!!open}"><span class="tree-arrow">${open?'▾':'▸'}</span><div><b>${c.name}</b><small>${c.code} · ${us.length} 個產品帳號</small></div><span>${qs.map(q=>`${q.name} ${Math.round(q.used/q.total*100)}%`).join(' ／ ')}</span>${status(serviceStatus(s,e).label)}</button>${open?`<div class="quota-company-body"><div class="company-quota-strip">${qs.map(q=>`<div><span>${q.name} · 公司共用額度</span><b>${q.used}<small> / ${q.total} ${q.unit}</small></b><div class="usage-bar ${q.used/q.total>=1?'bad':q.used/q.total>=.85?'warn':''}"><span style="width:${Math.min(100,q.used/q.total*100)}%"></span></div><small>重置日 ${q.reset}</small>${btn('調整公司額度','quotaEdit',`data-id="${q.id}"`,'small ghost')}</div>`).join('')}</div>${qs.length?'':note('這間公司尚未配置展示額度項目。')}<h3>客戶用戶使用明細</h3><div class="table-scroll"><table class="dash-table"><thead><tr><th>用戶／Email</th><th>角色</th><th>帳號狀態</th>${qs.map(q=>`<th>${q.name}</th>`).join('')}<th>額度來源</th><th>操作</th></tr></thead><tbody>${us.map(u=>`<tr><td><b>${u.name}</b><small>${u.email}</small></td><td>${u.role}</td><td>${status(u.status)}</td>${qs.map(q=>`<td>${s.usageByUser.find(r=>r.quota===q.id&&r.user===u.id)?.used||0} ${q.unit}</td>`).join('')}<td>共用公司額度</td><td>${btn('查看用戶明細','userUsage',`data-id="${u.id}"`,'small ghost')}</td></tr>`).join('')}<tr class="quota-total"><td colspan="3">公司用量合計</td>${qs.map(q=>`<td>${q.used} ${q.unit}</td>`).join('')}<td colspan="2">逐用戶明細加總</td></tr></tbody></table></div><p class="chart-footnote">用戶分攤數字為展示明細；邀請中與停用帳號於本期展示用量為 0。實際個別用戶獨立額度規則尚待確認。</p></div>`:''}</section>`;}).join('')||'<div class="dash-empty">沒有符合條件的公司</div>'}</div>`:''}</section>`;}).join('')}</div>`;
}
export function restoreDialog(s,v){const m=v.modal,d=m?.data||{};if(!m)return null;let title='',subtitle='',body='',footer='',drawer=true,wide=false;
  if(m.type==='productEdit'){const p=productOf(s,m.id)||{name:'',code:'',description:'',version:'v1.0.0',status:'開發中',owner:'王小明',billing:'公司訂閱'};title=m.id?'編輯產品':'新增產品';subtitle='產品資料與維護公告';body=field('產品名稱','name',d.name??p.name,'text','required')+field('產品代碼','code',d.code??p.code,'text','required')+restoreText('產品說明','description',d.description??p.description)+field('目前版本','version',d.version??p.version)+field('負責人','owner',d.owner??p.owner)+select('產品狀態','status',['已上線','運行正常','維護中','開發中','已下架'],d.status||p.status)+select('計費形式','billing',['公司訂閱','公司合約'],d.billing||p.billing)+(m.id?'':field('初始方案名額','limit',d.limit||5,'number','min="1" required'))+field('維護開始時間','maintenanceStart',(d.maintenanceStart??p.maintenanceStart)||'','datetime-local')+field('預計恢復時間','recovery',(d.recovery??p.recovery)||'','datetime-local')+restoreText('維護公告','notice',(d.notice??p.notice)||'')+note('產品總開關獨立透過確認操作管理；產品資訊編輯不會略過確認而改變所有客戶使用權。')+restoreReason(d);footer=btn('儲存產品','submitProductEdit','','primary');}
  if(m.type==='companyEdit'){const c=companyOf(s,m.id)||{name:'',short:'',code:'',industry:'',contact:'',email:'',owner:'王小明',note:''};const ps=d.product||'e2b';title=m.id?'編輯客戶公司':'新增使用客戶';subtitle='已在使用服務的公司資料，不包含 CRM 或業務開發流程';body=field('公司名稱','name',d.name??c.name,'text','required')+field('公司簡稱','short',d.short??c.short)+field('客戶代碼','code',d.code??c.code,'text','required')+field('產業','industry',d.industry??c.industry)+field('聯絡人','contact',d.contact??c.contact)+field('Email','email',d.email??c.email,'email','required')+field('內部負責人','owner',d.owner??c.owner)+restoreText('備註','note',d.note??c.note)+(m.id?'':select('已開通產品','product',s.products.map(p=>[p.id,p.name]),ps)+select('公司方案','plan',s.plans.filter(p=>p.product===ps).map(p=>[p.id,p.name]),d.plan)+field('服務開始日','start',d.start||DEMO_DATE,'date','required')+field('服務到期日','end',d.end||'2027-10-04','date','required'))+restoreReason(d);footer=btn('儲存客戶公司','submitCompanyEdit','','primary');}
  if(m.type==='entitlementEdit'){const e=s.entitlements.find(e=>e.id===m.id);title='管理產品使用權';subtitle=`${companyOf(s,e.company).short} / ${productOf(s,e.product).name}`;body=select('方案','plan',s.plans.filter(p=>p.product===e.product).map(p=>[p.id,p.name]),d.plan||e.plan)+select('服務類型','mode',['正式服務','試用'],d.mode||e.mode||'正式服務')+select('開通階段','stage',['已開通','等待開通'],d.stage||e.stage||'已開通')+select('付款狀態','payment',['已付款','付款逾期','待付款','合約服務'],d.payment||e.payment)+field('服務開始日','start',d.start||e.start,'date','required')+field('服務到期日','end',d.end||e.end,'date','required')+restoreText('使用權備註','note',(d.note??e.note)||'')+note('試用功能仍依明確開放範圍與客戶功能設定判斷，不以清單前兩項決定。')+restoreReason(d)+`<label class="checkbox"><input type="checkbox" name="confirm" required>我已確認操作範圍與影響</label>`;footer=btn('儲存使用權','submitEntitlementEdit','','primary');}
  if(m.type==='companyTerm'){const es=s.entitlements.filter(e=>e.company===m.id),e=es.find(e=>e.id===d.entitlement)||es[0];title='延長產品使用期限';subtitle=companyOf(s,m.id).name;body=select('選擇產品使用權','entitlement',es.map(e=>[e.id,productOf(s,e.product).name+' · 原到期 '+e.end]),e.id)+field('延長後到期日','end',d.end||e.end,'date','required')+note('僅延長所選產品，不縮短原期限，也不解除公司或產品暫停。')+restoreReason(d)+`<label class="checkbox"><input type="checkbox" name="confirm" required>我已確認操作範圍與影響</label>`;footer=btn('確認延長期限','submitCompanyTerm','','primary');}
  if(m.type==='legacyStaff'){const u=s.staff.find(u=>u.id===m.id)||{name:'',email:'',department:'',role:'',scope:'全系統',status:'邀請中',actions:[],modules:[]};title=m.id?'編輯內部帳號':'新增管理帳號';subtitle='職員資料、管理範圍與可操作模組';body=field('姓名','name',d.name??u.name,'text','required')+field('Email','email',d.email??u.email,'email','required')+field('部門','department',(d.department??u.department)||'')+field('職稱','role',d.role??u.role)+select('管理範圍','scope',['全系統',...s.products.map(p=>p.name),'唯讀'],d.scope||u.scope)+`<fieldset><legend>可操作模組</legend>${['產品管理','客戶公司','營運管理','系統管理'].map(x=>`<label class="checkbox"><input type="checkbox" name="modules" value="${x}" ${(d.modules||u.modules||[]).includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset><fieldset><legend>動作權限</legend>${['檢視','編輯','發布','停用','系統管理','匯出'].map(x=>`<label class="checkbox"><input type="checkbox" name="actions" value="${x}" ${(d.actions||u.actions).includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset>`+restoreReason(d)+note(m.id?'停用或恢復帳號請使用清單的獨立確認操作。':'建立後呈現邀請已寄出／等待啟用階段，不會真實寄信。');footer=btn('儲存管理帳號','submitLegacyStaff','','primary');}
  if(m.type==='staffState'||m.type==='resetPassword'){const u=s.staff.find(u=>u.id===m.id);drawer=false;title=m.type==='resetPassword'?'重設密碼通知確認':u.status==='停用'?'恢復管理帳號':'停用管理帳號';subtitle=`${u.name} / ${u.email}`;body=note(m.type==='resetPassword'?'確認後建立重設密碼通知的展示紀錄，不會修改密碼或真的寄信。':'只影響內部管理帳號；不影響客戶產品帳號。')+restoreReason(d)+`<label class="checkbox"><input type="checkbox" name="confirm" required>我已確認操作範圍與影響</label>`;footer=btn('確認操作',m.type==='resetPassword'?'submitResetPassword':'submitStaffState','','primary');}
  if(m.type==='notificationRule'){const r=s.notificationRules.find(r=>r.id===m.id);title='通知規則設定';subtitle=r.name;body=select('規則狀態','enabled',[['true','已啟用'],['false','已停用']],d.enabled??String(r.enabled))+select('寄送管道','channel',['Email','站內通知','Email、後台站內通知'],d.channel||r.channel)+field('觸發條件','condition',d.condition??r.condition,'text','required')+restoreReason(d);footer=btn('儲存通知規則','submitNotificationRule','','primary');}
  if(m.type==='task'){const t=s.tasks.find(t=>t.id===m.id);title='待處理事項';subtitle=t.title;body=note(esc(t.desc))+select('處理狀態','state',['待處理','處理中','已處理'],d.state||t.state)+field('負責人','owner',d.owner||t.owner)+restoreReason(d);footer=btn('儲存處理紀錄','submitTask','','primary');}
  if(m.type==='userUsage'){const u=s.users.find(u=>u.id===m.id),qs=s.quotas.filter(q=>q.company===u.company&&q.product===u.product);title='用戶使用明細';subtitle=`${productOf(s,u.product).name} → ${companyOf(s,u.company).short} → ${u.name}`;body=note(u.email)+qs.map(q=>section(q.name,'本期共用公司額度',`<dl class="definition-grid"><div><dt>用戶本期用量</dt><dd>${s.usageByUser.find(r=>r.quota===q.id&&r.user===u.id)?.used||0} ${q.unit}</dd></div><div><dt>公司共用上限</dt><dd>${q.total} ${q.unit}</dd></div><div><dt>公司已使用</dt><dd>${q.used} ${q.unit}</dd></div><div><dt>重置日</dt><dd>${q.reset}</dd></div></dl>`)).join('')+note('用戶數值為展示明細；不將公司額度當作每個用戶各自的額度。');footer=btn('關閉','closeModal','','primary');}
  if(m.type==='assetEdit'){const a=assetOf(s,m.id),brand=assetKind(s,m.id)==='brand';title=brand?'編輯品牌樣式資料':'編輯內容版型資料';subtitle='官網方案專屬資產';body=field('名稱','name',d.name??a.name,'text','required')+field('代碼','code',d.code??a.code,'text','required')+field('負責人','owner',d.owner??a.owner)+restoreText('說明','description',d.description??a.description)+(brand?field('字體','font',d.font??a.font):field('呈現方式','layout',d.layout??a.layout))+field('套件內容','files',(d.files??a.files)||'')+note('此處編輯資產資料；視覺、內容或版本變更請使用「建立新版」，經檢查與發布確認後生效。')+restoreReason(d);footer=btn('儲存資產資料','submitAssetEdit','','primary');}
  return title?{title,subtitle,body,footer,drawer,wide}:null;
}
export function executeRestore(action,m,d,s,log){
  const actions=['submitCompanyTerm','submitProductEdit','submitCompanyEdit','submitEntitlementEdit','submitLegacyStaff','submitStaffState','submitResetPassword','submitNotificationRule','submitTask','submitAssetEdit'];if(!actions.includes(action))return null;
  let before='尚未建立',after='已儲存',target='',module='資料管理';
  if(action==='submitCompanyTerm'){const e=s.entitlements.find(e=>e.id===d.entitlement&&e.company===m.id);if(!e)throw Error('請選擇此公司的產品使用權。');if(d.end<=e.end)throw Error('延長後期限必須晚於原本期限。');before=e.end;e.end=d.end;after=e.end;target=companyOf(s,m.id).short+' / '+productOf(s,e.product).name;module='產品期限';}
  if(action==='submitProductEdit'){let p=productOf(s,m.id);if(s.products.some(x=>x.id!==m.id&&x.code===d.code))throw Error('產品代碼已存在。');if(!p){p={id:`product-${Date.now()}`,enabled:false};s.products.push(p);s.plans.push({id:`plan-${p.id}`,product:p.id,name:d.name+' · 初始方案',limit:Number(d.limit),note:'展示方案'});}else before=p.name+' / '+p.status;Object.assign(p,{name:d.name,code:d.code,description:d.description,version:d.version,status:d.status,owner:d.owner,billing:d.billing,maintenanceStart:d.maintenanceStart,recovery:d.recovery,notice:d.notice,updated:DEMO_DATE});target=p.name;after=p.name+' / '+p.status;module='產品管理';}
  if(action==='submitCompanyEdit'){let c=companyOf(s,m.id);if(s.companies.some(x=>x.id!==m.id&&x.code===d.code))throw Error('客戶代碼已存在。');if(!c){const plan=s.plans.find(p=>p.id===d.plan&&p.product===d.product);if(!plan)throw Error('請選擇所屬產品的方案。');if(d.end<d.start)throw Error('到期日不可早於開始日。');c={id:`company-${Date.now()}`,enabled:true};s.companies.push(c);s.entitlements.push({id:`entitlement-${Date.now()}`,company:c.id,product:d.product,plan:d.plan,start:d.start,end:d.end,enabled:true,payment:'已付款',mode:'正式服務',stage:'已開通'});}else before=c.name;Object.assign(c,{name:d.name,short:d.short||d.name,code:d.code,industry:d.industry,contact:d.contact,email:d.email,owner:d.owner,note:d.note,updated:DEMO_DATE});target=c.name;after=c.name+' / 公司資料完整';module='客戶公司';}
  if(action==='submitEntitlementEdit'){const e=s.entitlements.find(e=>e.id===m.id),plan=s.plans.find(p=>p.id===d.plan&&p.product===e.product);if(!plan)throw Error('方案與產品不相符。');if(d.end<d.start)throw Error('到期日不可早於開始日。');if(seats(s,e).used>plan.limit)throw Error('目前啟用與邀請中帳號超過新方案名額，請先處理帳號再調整。');before=`${e.mode||'正式服務'} / ${e.end}`;Object.assign(e,{plan:d.plan,mode:d.mode,stage:d.stage,payment:d.payment,start:d.start,end:d.end,note:d.note});after=`${e.mode} / ${e.end} / ${e.stage}`;target=companyOf(s,e.company).short+' / '+productOf(s,e.product).name;module='產品使用權';}
  if(action==='submitLegacyStaff'){let u=s.staff.find(u=>u.id===m.id);if(s.staff.some(x=>x.id!==m.id&&x.email===d.email))throw Error('管理帳號 Email 已存在。');if(!u){u={id:`staff-${Date.now()}`,status:'邀請中',lastLogin:'尚未登入'};s.staff.push(u);}else before=u.name+' / '+u.scope;Object.assign(u,{name:d.name,email:d.email,department:d.department,role:d.role,scope:d.scope,actions:d.actions,modules:d.modules});after=u.name+' / '+u.scope+' / '+u.status;target=u.name;module='內部帳號';}
  if(action==='submitStaffState'||action==='submitResetPassword'){const u=s.staff.find(u=>u.id===m.id);before=u.status;target=u.name;module='內部帳號';if(action==='submitStaffState'){if(u.id==='s1')throw Error('展示主操作帳號不可停用。');u.status=u.status==='停用'?'啟用':'停用';after=u.status;}else{after='重設密碼通知已建立（展示）';s.notifications.unshift({id:`reset-${Date.now()}`,name:'管理帳號重設密碼：'+u.name,company:'internal',product:'e2b',channel:'Email',status:'已發送',time:DEMO_DATE+' 10:00',content:'重設密碼通知展示，收件人 '+u.email+'，沒有實際寄送。'});}}
  if(action==='submitNotificationRule'){const r=s.notificationRules.find(r=>r.id===m.id);before=r.enabled?'啟用':'停用';Object.assign(r,{enabled:d.enabled==='true',channel:d.channel,condition:d.condition});after=(r.enabled?'啟用':'停用')+' / '+r.condition;target=r.name;module='通知規則';}
  if(action==='submitTask'){const t=s.tasks.find(t=>t.id===m.id);before=t.state;Object.assign(t,{state:d.state,owner:d.owner});after=t.state;target=t.title;module='待處理事項';}
  if(action==='submitAssetEdit'){const a=assetOf(s,m.id);before=a.name;Object.assign(a,{name:d.name,code:d.code,owner:d.owner,description:d.description,files:d.files,updated:DEMO_DATE});if(assetKind(s,a.id)==='brand')a.font=d.font;else a.layout=d.layout;after=a.name;target=a.name;module='官網資產';}
  log('儲存'+module,target,before,after,d.reason,module);return {message:'已更新畫面與操作紀錄。',before,after};
}
