import {dashboard} from './dashboard.js';
import {restorePage,restoreDialog,executeRestore,notificationRules,quotaHierarchy} from './restore.js';
import { DEMO_DATE,seedState } from './data.js';
import { companyOf,productOf,entitlementOf,canActivate,daysUntil } from './model.js';
import { esc,btn,status } from './ui.js';
import { navigation,titles,basicPage } from './screens.js';
import { assetList,assetDetail,wizardPage,releaseDetail,assetOf,assetKind,affectedSites } from './assets.js';
import { renderDialog } from './dialogs.js';

let data=seedState();
const view={dashProduct:'all',dashPeriod:90,dashMetric:'rights',notificationTab:'records',quotaExpanded:{},page:'overview',id:'',query:'',filter:'全部',sort:'default',productFilter:'all',companyProduct:'e2b',detailTab:'users',productTab:'features',assetTab:'definition',settingsTab:'rules',releaseStage:'',device:'desktop',checkScenario:'pass',tablePages:{},modal:null,wizard:null,mobileNav:false};
const root=document.querySelector('#root');let lastFocus=null;
function currentTitle(){if(view.page==='company')return ['公司服務管理','公司 → 產品使用權 → 產品用戶'];if(view.page==='product')return ['產品管理','全域產品與功能的服務控制。'];if(view.page==='asset')return [assetKind(data,view.id)==='brand'?'品牌樣式管理':'內容版型管理','定義、檢查、預覽與發布階段。'];if(view.page==='wizard')return ['官網資產工作流程','預設階段畫面可直接切換。'];if(view.page==='release')return ['發布詳情','從草稿到結果的階段展示。'];return titles[view.page]||titles.overview;}
function activePage(){return view.page==='company'?'companies':view.page==='product'?'products':view.page==='asset'?'products':view.page==='wizard'?'products':view.page==='release'?'releases':view.page;}
function headerActions(){if(view.page==='overview')return '';if(view.page==='companies')return btn('新增使用客戶','companyEdit','','primary');if(view.page==='plans')return btn('新增產品方案','planEdit','','primary');if(view.page==='products')return btn('新增產品','productEdit','','primary');if(view.page==='staff')return btn('新增管理帳號','legacyStaff','','primary');if(view.page==='features')return btn('新增功能','newFeature',`data-product="${view.productFilter==='all'?'e2b':view.productFilter}"`,'primary');if(view.page==='product'&&view.id==='web'&&['brands','blocks'].includes(view.productTab))return btn(view.productTab==='brands'?'上傳品牌樣式':'上傳內容版型','newAsset',`data-kind="${view.productTab==='brands'?'brand':'block'}"`,'primary');if(view.page==='product')return btn('編輯產品','productEdit',`data-id="${view.id}"`)+btn('新增功能','newFeature',`data-product="${view.id}"`,'primary');if(view.page==='brands'||view.page==='blocks')return btn(view.page==='brands'?'建立品牌樣式':'建立內容版型','newAsset',`data-kind="${view.page==='brands'?'brand':'block'}"`,'primary');if(view.page==='notifications')return btn('建立通知草稿','newNotification','','primary');if(view.page==='releases')return btn('建立發布','newRelease','','primary');if(view.page==='company')return `<select aria-label="公司展示情境" data-view="companyScenario">${data.companies.map(c=>`<option value="${c.id}" ${view.id===c.id?'selected':''}>${c.short}${c.id==='c1'?' · 單一產品到期':c.id==='c3'?' · 名額額滿':c.id==='c6'?' · 公司暫停':c.id==='c8'?' · 單一產品暫停':''}</option>`).join('')}</select>`;return '';}
function pageBody(){if(view.page==='product'&&view.id==='web'&&['brands','blocks'].includes(view.productTab))return `<div class="web-assets-context">${btn('← 返回官網功能管理','productTab','data-tab="features"','ghost')}${btn('品牌樣式','productTab','data-tab="brands"',view.productTab==='brands'?'selected':'ghost')}${btn('內容版型','productTab','data-tab="blocks"',view.productTab==='blocks'?'selected':'ghost')}</div>`+assetList(data,{...view,page:view.productTab});if(view.page==='overview')return dashboard(data,view);if(view.page==='quotas')return quotaHierarchy(data,view);const restored=restorePage(data,view);if(restored!==null)return restored;if(view.page==='brands'||view.page==='blocks')return assetList(data,view);if(view.page==='asset')return assetDetail(data,view);if(view.page==='wizard')return wizardPage(data,view);if(view.page==='release')return releaseDetail(data,view);return basicPage(data,view);}
function render(){const [title,desc]=currentTitle();const active=activePage();root.innerHTML=`<a class="skip-link" href="#workspace">跳至主要內容</a><div class="app ${view.mobileNav?'nav-open':''}"><aside class="sidebar"><div class="brand"><span class="brand-mark">DS</span><div><b>總控台</b><small>Service Operations</small></div></div><div class="workspace-label"><span class="workspace-dot"></span>公司營運工作區</div><nav aria-label="主要導覽">${navigation.map(([group,items])=>`<div class="nav-group"><span>${group}</span>${items.map(([id,label])=>`<button data-page="${id}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${label}${id==='notifications'?`<small>${data.notifications.filter(n=>['草稿','待發送','發送失敗'].includes(n.status)).length}</small>`:''}</button>`).join('')}</div>`).join('')}</nav><div class="sidebar-bottom"><div class="admin-avatar">王</div><div><b>王小明</b><small>系統管理員</small></div><span class="admin-status"></span></div></aside><div class="main-shell"><header class="utility-bar"><div><button class="mobile-menu" data-action="mobileNav" aria-label="切換導覽">選單</button><span>DS / 公司產品與客戶管理</span></div><div><span class="environment">展示模式</span><span class="mono">${DEMO_DATE}</span>${btn('重置展示','reset','','small ghost')}</div></header><main id="workspace" tabindex="-1"><div class="page-header"><div><div class="breadcrumb">營運工作區 <span>/</span> ${title}${['company','product','asset','release','wizard'].includes(view.page)?` <span>/</span> ${btn('返回清單','back','','text')}`:''}</div><h1>${title}</h1><p>${desc}</p></div><div class="page-actions">${headerActions()}</div></div><div class="page-body ${view.page==='overview'?'dashboard-shell':''}">${pageBody()}</div><footer class="workspace-footer"><span>DS 總控台 · 需求與流程展示</span><span>方案與數值為展示資料；重新整理即回復預設情境。</span></footer></main></div></div>${renderDialog(data,view)}<div id="toast" class="toast" role="status" hidden></div>`;if(view.modal){document.querySelector('.dialog')?.focus();} }
function navigate(page,id='',product=''){if(page==='users'||page==='entitlements')page='companies';if(page==='features')page='products';view.page=page;view.id=id;view.query='';view.filter='全部';view.sort='default';view.productFilter='all';view.tablePages={};view.modal=null;view.mobileNav=false;view.releaseStage='';if(page==='company'){view.companyProduct=product||'e2b';view.detailTab='users';}if(page==='product')view.productTab='features';if(page==='asset'){view.assetTab='definition';view.checkScenario=assetOf(data,id)?.status==='檢查失敗'?'fail':'pass';}render();window.scrollTo({top:0,behavior:'instant'});}
function openModal(type,props={}){lastFocus=document.activeElement;view.modal={type,...props,data:{}};render();}
function closeModal(){const action=lastFocus?.dataset.action,id=lastFocus?.dataset.id;view.modal=null;render();const restored=[...document.querySelectorAll('button')].find(b=>action&&b.dataset.action===action&&b.dataset.id===id);(restored||document.querySelector('#workspace'))?.focus();}
function result(message,before,after,subtitle){view.modal={type:'result',message,before,after,subtitle,data:{}};render();}
function collectForm(){const form=document.querySelector('#dialogForm');if(!form)return {};const fd=new FormData(form);const d=Object.fromEntries(fd);d.clients=fd.getAll('clients');d.actions=fd.getAll('actions');d.modules=fd.getAll('modules');d.releaseChecks=fd.getAll('releaseChecks');d.notify=fd.has('notify');d.confirm=fd.has('confirm');return d;}
function validForm(){const form=document.querySelector('#dialogForm');return form?.reportValidity();}
function error(message){const el=document.querySelector('#formError');el.hidden=false;el.textContent=message;}
function addLog(action,target,before,after,reason,module='服務管理'){data.logs.unshift({id:`log-${Date.now()}`,time:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date()),actor:'王小明',module,action,target,before,after,reason});}
function captureWizard(){const form=document.querySelector('#wizardForm');if(!form)return;const f=new FormData(form);const w=view.wizard;for(const [key,val] of f.entries()){if(key.startsWith('asset')&&key!=='assetFile')w[key.slice(5).toLowerCase()]=val;}if(w.step===4)w.clients=f.getAll('testCompanies');}
function saveWizardAsset(w,published){let a=assetOf(data,w.source);if(!a){a={id:`${w.kind}-${Date.now()}`,versions:[],font:'Noto Sans TC',layout:'自訂內容結構'};(w.kind==='brand'?data.brands:data.blocks).unshift(a);w.source=a.id;}Object.assign(a,{name:w.name,code:w.code,owner:w.owner,description:w.description,color:w.color,category:w.category||'服務入口',updated:DEMO_DATE});if(published||!a.version)a.version=w.version;if(published||a.versions.length===0)a.status=published?'已發布':w.stage;a.pendingVersion=published?'':w.version;a.pendingStage=published?'':w.stage;if(!a.versions.includes(w.version))a.versions.unshift(w.version);return a;}
function sensitiveSubmit(){if(!validForm())return;const m=view.modal,d=collectForm();let before,after,target;
  if(m.kind==='company'){const c=companyOf(data,m.id);before=c.enabled?'正常':'公司已暫停';c.enabled=!c.enabled;after=c.enabled?'解除公司暫停；各產品仍依期限與狀態判斷':'公司所有產品帳號不可使用';target=c.name;}
  if(m.kind==='entitlement'){const e=data.entitlements.find(e=>e.id===m.id);before=e.enabled?'使用權未暫停':'產品已暫停';e.enabled=!e.enabled;after=e.enabled?'解除此產品暫停，其他限制仍保留':'此產品下帳號不可使用，另一產品不受影響';target=`${companyOf(data,e.company).short} / ${productOf(data,e.product).name}`;}
  if(m.kind==='user'){const u=data.users.find(u=>u.id===m.id);if(u.status==='停用'){const allowed=canActivate(data,u);if(!allowed.ok)return error(allowed.reason);}before=u.status;u.status=u.status==='停用'?'啟用':'停用';after=u.status==='停用'?'停用，不占名額':'啟用，占用 1 席';target=`${companyOf(data,u.company).short} / ${productOf(data,u.product).name} / ${u.name}`;}
  if(m.kind==='product'){const p=productOf(data,m.id);before=p.enabled?'總開關開啟':'總開關關閉';p.enabled=!p.enabled;after=p.enabled?'總開關開啟，依客戶使用權判斷':'全域停用，所有該產品帳號不可使用';target=p.name;p.recovery=d.recovery;}
  if(m.kind==='feature'){const f=data.features.find(f=>f.id===m.id);before=f.enabled?'功能開啟':'功能關閉';f.enabled=!f.enabled;after=f.enabled?'功能開啟':'功能停用';if(f.enabled&&f.status==='維護中')f.status=f.scope==='全部客戶'?'已釋出':f.scope==='指定客戶'?'指定客戶測試':'內部測試';target=f.name;f.recovery=d.recovery;}
  addLog('服務狀態調整',target,before,after,d.reason);if(d.notify){const source=m.kind==='user'?data.users.find(x=>x.id===m.id):m.kind==='entitlement'?data.entitlements.find(x=>x.id===m.id):m.kind==='feature'?data.features.find(x=>x.id===m.id):null;const products=m.kind==='company'?data.entitlements.filter(x=>x.company===m.id).map(x=>x.product):[m.kind==='product'?m.id:source?.product];for(const product of new Set(products))data.notifications.unshift({id:`n-${Date.now()}-${product}`,name:`服務狀態調整：${target}`,company:m.kind==='company'?m.id:source?.company||'all',product,channel:'站內通知',status:'草稿',time:'尚未排程',content:`${target}：${after}。原因：${d.reason}`});}result(`已呈現${target}的變更結果。`,before,after);
}
function submit(type){if(type==='submitSensitive')return sensitiveSubmit();if(type==='submitReset'){data=seedState();view.modal=null;navigate('overview');return;}if(!validForm())return;const m=view.modal,d=collectForm();try{const restored=executeRestore(type,m,d,data,addLog);if(restored)return result(restored.message,restored.before,restored.after);}catch(e){return error(e.message);}
  if(type==='submitTerm'){const e=data.entitlements.find(e=>e.id===m.id);if(m.extendOnly&&d.end<=e.end)return error('延長期限必須晚於原本到期日。');if(d.end<e.start)return error('到期日不可早於使用起始日。');const before=e.end;e.end=d.end;const target=`${companyOf(data,e.company).short} / ${productOf(data,e.product).name}`;addLog('修改使用期限',target,before,e.end,d.reason,'產品使用權');return result('只修改所選產品的使用期限。',before,e.end,target);}
  if(type==='submitAccess'){const f=data.features.find(f=>f.id===m.id);const before=data.overrides.find(o=>o.company===m.company&&o.feature===m.id)?.mode||'系統預設';data.overrides=data.overrides.filter(o=>!(o.company===m.company&&o.feature===m.id));if(d.mode==='強制關閉')data.overrides.push({company:m.company,feature:m.id,mode:d.mode,reason:d.reason,start:DEMO_DATE,end:''});addLog('調整客戶功能權限',`${companyOf(data,m.company).short} / ${f.name}`,before,d.mode,d.reason,'功能權限');return result('已呈現客戶權限設定。',before,d.mode);}
  if(type==='submitFeature'){let f=data.features.find(f=>f.id===m.id);if(!f){if(data.features.some(x=>x.product===m.product&&x.code===d.code))return error('此產品已有相同功能代碼。');f={id:`feature-${Date.now()}`,product:d.product||m.product,enabled:true,scope:'僅內部測試',clients:[],status:'內部測試'};}if(d.scope==='指定客戶'&&!d.clients.length)return error('請至少選擇一間指定客戶。');const before=m.id?f.scope:'尚未建立';if(!m.id)data.features.push(f);Object.assign(f,{name:d.name,code:d.code,scope:d.scope,clients:d.clients,version:d.version,owner:d.owner||f.owner||'王小明',description:d.description,plannedAt:d.plannedAt,notice:d.notice,updated:DEMO_DATE});if(f.status!=='維護中')f.status=d.scope==='全部客戶'?'已釋出':d.scope==='指定客戶'?'指定客戶測試':'內部測試';addLog('修改功能開放範圍',f.name,before,f.scope,d.reason,'產品與功能');return result('已呈現功能設定結果。',before,f.scope);}
  if(type==='submitQuota'){const q=data.quotas.find(q=>q.id===m.id);const total=Number(d.total);if(total<q.used)return error('總額度不能低於目前已使用量。');if(d.expiry&&daysUntil(d.expiry)<0)return error('臨時額度結束日不能早於展示基準日。');const before=`${q.used} / ${q.total} ${q.unit}`;q.total=total;q.expiry=d.expiry;const after=`${q.used} / ${q.total} ${q.unit}${d.expiry?`，臨時額度至 ${d.expiry}`:''}`;addLog('調整使用額度',`${companyOf(data,q.company).short} / ${q.name}`,before,after,d.reason,'使用量與額度');return result('已呈現額度調整前後。',before,after);}
  if(type==='submitNotification'){let n=data.notifications.find(n=>n.id===m.id);const before=n?.status||'尚未建立';const row={id:n?.id||`notification-${Date.now()}`,name:d.name,company:d.company,product:d.product,channel:d.channel,status:d.stage,content:d.content,time:d.time?d.time.replace('T',' '):'尚未排程'};if(n)Object.assign(n,row);else data.notifications.unshift(row);return result('通知階段已保存於本次展示，不會真的寄送。',before,row.status);}
  if(type==='submitAsset'){const a=assetOf(data,m.id)||m.asset;const brand=m.asset?m.kind==='brand':assetKind(data,a.id)==='brand';const before=a.version||'尚未發布';const after=m.type==='assetRetire'?d.retire:m.version||view.wizard?.version||'v1.5.0';const real=m.asset&&view.wizard?saveWizardAsset(view.wizard,true):assetOf(data,m.id);if(real&&m.type!=='assetRetire'){real.version=after;real.status='已發布';if(!real.versions.includes(after))real.versions.unshift(after);if(brand)affectedSites(data,a.id).forEach(w=>{w.version=after;w.updated=DEMO_DATE;});}if(real&&m.type==='assetRetire')real.status='已下架';if(real&&m.asset){data.releases.unshift({id:`release-${Date.now()}`,name:real.name+' '+after,product:'web',type:brand?'品牌樣式':'內容版型',asset:real.id,version:after,scope:brand?'所有採用網站':'待確認內容更新策略',status:'已發布',time:DEMO_DATE+' 10:00',owner:real.owner,description:real.description});}addLog(m.type==='assetRollback'?'回復版本':m.type==='assetRetire'?'下架資產':'發布資產',a.name,before,after,d.reason,brand?'品牌樣式':'內容版型');return result(brand&&m.type!=='assetRetire'?`所有 ${affectedSites(data,a.id).length} 個採用網站同步更新的結果已呈現。`:'已呈現所選資產操作結果。',before,after);}
  if(type==='submitStaff'){const u=data.staff.find(u=>u.id===m.id);const before=u.actions.join('、');Object.assign(u,{name:d.name,role:d.role,scope:d.scope,actions:d.actions});addLog('內部權限展示設定',u.name,before,u.actions.join('、'),d.reason,'內部帳號');return result('已呈現內部帳號權限提案。',before,u.actions.join('、'));}
  if(type==='submitRelease'){if(d.scope==='指定客戶'&&!d.clients.length)return error('請至少選擇一間指定客戶。');if((d.releaseType==='內容版型'||d.releaseType==='品牌樣式')&&d.product!=='web')return error('官網資產必須綁定官網產品。');if(d.releaseType==='品牌樣式')return error('品牌樣式請從品牌樣式詳情建立新版，以完整確認採用網站。');data.releases.unshift({id:`release-${Date.now()}`,name:d.name,product:d.product,type:d.releaseType,asset:d.product,version:d.version,scope:d.scope,clients:d.clients,releaseChecks:d.releaseChecks,status:'草稿',time:d.time.replace('T',' '),owner:'王小明',description:d.description});return result('展示發布草稿已建立，可從清單查看各階段。');}
  if(type==='submitSetting'){data.settings[m.label]=d.value;addLog('系統設定',m.label,'原設定',d.value,'展示設定調整','系統設定');return result(`${m.label}：${d.value}（展示設定）。`);}
}
root.addEventListener('click',event=>{const el=event.target.closest('button');if(!el||el.disabled)return;event.preventDefault();if(el.dataset.page){navigate(el.dataset.page,el.dataset.id,el.dataset.product);if(el.dataset.preset)view.filter=el.dataset.preset;if(el.dataset.productFilter)view.productFilter=el.dataset.productFilter;if(el.dataset.preset||el.dataset.productFilter)render();return;}const a=el.dataset.action,id=el.dataset.id;
  if(a?.startsWith('submit')){submit(a);return;}
  if(a==='dashMetric'){view.dashMetric=el.dataset.value;render();return;}if(a==='refreshDashboard'){render();return;}if(a==='notificationTab'){view.notificationTab=el.dataset.tab;render();return;}if(a==='quotaExpand'){view.quotaExpanded[el.dataset.key]=!view.quotaExpanded[el.dataset.key];render();return;}if(a==='extendTerm'){openModal('term',{id,extendOnly:true});return;}if(['planEdit','companyTerm','companyEdit','productEdit','entitlementEdit','legacyStaff','staffState','resetPassword','notificationRule','task','assetEdit','userUsage'].includes(a)){openModal(a,{id});return;}if(a==='quotaDrill'){navigate('quotas');view.quotaExpanded[el.dataset.product]=true;view.quotaExpanded[el.dataset.product+'-'+el.dataset.company]=true;render();return;}if(a==='closeModal'){closeModal();return;}
  if(a==='reset'){openModal('reset');return;}
  if(a==='mobileNav'){view.mobileNav=!view.mobileNav;render();return;}
  if(a==='back'){if(['asset','wizard'].includes(view.page)){const tab=view.page==='asset'?(assetKind(data,view.id)==='brand'?'brands':'blocks'):(view.wizard.kind==='brand'?'brands':'blocks');navigate('product','web');view.productTab=tab;render();return;}navigate(activePage());return;}
  if(a==='openCompany'){navigate('company',id,el.dataset.product);return;}
  if(a==='openProduct'){navigate('product',id);return;}
  if(a==='openAsset'){navigate('asset',id);return;}
  if(a==='tablePage'){view.tablePages[el.dataset.key]=Number(el.dataset.value);render();return;}
  const tabMap={companyProduct:'companyProduct',detailTab:'detailTab',productTab:'productTab',assetTab:'assetTab',settingsTab:'settingsTab',releaseStage:'releaseStage'};
  if(tabMap[a]){view[tabMap[a]]=el.dataset.tab;view.query='';view.filter='全部';view.tablePages={};if(a==='companyProduct')view.detailTab='users';render();return;}
  if(a==='sensitive'){openModal('sensitive',{kind:el.dataset.kind,id});return;}
  const modalMap={editTerm:'term',inspectAccess:'access',featureSettings:'feature',quotaEdit:'quota',notification:'notification',log:'log',userInfo:'userInfo',staff:'staff',assetRetire:'assetRetire'};
  if(modalMap[a]){openModal(modalMap[a],{id,company:el.dataset.company});return;}
  if(a==='setting'){openModal('setting',{label:el.dataset.label});return;}
  if(a==='newNotification'){openModal('notification');return;}
  if(a==='newFeature'){openModal('feature',{product:el.dataset.product||'e2b'});return;}if(a==='newRelease'){openModal('releaseNew');return;}
  if(a==='previewSite'){openModal('preview',{id});return;}
  if(a==='assetVersionPreview'){openModal('preview',{asset:id,version:el.dataset.version});return;}
  if(a==='assetRollback'){openModal('assetRollback',{id,version:el.dataset.version});return;}
  if(a==='assetPublish'){openModal('assetPublish',{id,version:assetOf(data,id).pendingVersion||data.releases.find(r=>r.asset===id&&r.status==='待發布')?.version||assetOf(data,id).version});return;}
  if(a==='previewDevice'){view.device=el.dataset.device;render();return;}
  if(a==='newAsset'){const old=assetOf(data,id);view.wizard={kind:el.dataset.kind,source:id||'',step:0,name:old?.name||(el.dataset.kind==='brand'?'新品牌樣式':'新內容版型'),code:old?.code||(el.dataset.kind==='brand'?'BRAND-NEW':'BLOCK-NEW'),version:'v1.5.0',color:old?.color||'#185b79',owner:'張凱文',description:'調整視覺細節與手機呈現。',stage:'待發布',clients:['c1','c7']};navigate('wizard');return;}
  if(a==='wizardStep'){captureWizard();view.wizard.step=Number(el.dataset.step);render();return;}
  if(a==='cancelWizard'){const tab=view.wizard.kind==='brand'?'brands':'blocks';navigate('product','web');view.productTab=tab;render();return;}
  if(a==='demoFile'){captureWizard();view.wizard.file=view.wizard.kind==='brand'?'brand-package.zip':'content-package.zip';render();return;}
  if(a==='wizardFinish'){captureWizard();const w=view.wizard;if(!w.name||!w.code||!w.version){w.step=0;render();return;}if(w.stage==='待發布'&&view.checkScenario==='fail'){w.step=2;render();return;}if(w.stage!=='待發布'){const a=saveWizardAsset(w,false);addLog('儲存資產階段',a.name,'未儲存',w.stage,'展示階段設定',w.kind==='brand'?'品牌樣式':'內容版型');result('已儲存展示階段，可返回清單查看。','未儲存',w.stage);return;}openModal('assetPublish',{id:w.source,kind:w.kind,asset:{id:w.source||'new',name:w.name,version:assetOf(data,w.source)?.version||'尚未發布'},version:w.version});}
});
root.addEventListener('change',event=>{const el=event.target;if(el.dataset.view){const k=el.dataset.view;if(k==='companyScenario'){navigate('company',el.value);return;}view[k]=el.value;view.tablePages={};render();return;}if(el.name==='assetStage'){captureWizard();render();return;}if(el.name==='assetFile'){captureWizard();const file=el.files?.[0];if(file)view.wizard.file=file.name;render();return;}if(view.modal&&el.closest('#dialogForm')){view.modal.data=collectForm();if(el.name==='product'&&['releaseNew','companyEdit','planEdit'].includes(view.modal.type))view.modal.data.clients=[];if(el.name==='entitlement'&&view.modal.type==='companyTerm'){delete view.modal.data.end;render();return;}if(el.name==='scope'||el.name==='stage'||(el.name==='product'&&['releaseNew','companyEdit','feature','planEdit'].includes(view.modal.type)))render();}});
root.addEventListener('input',event=>{const el=event.target;if(el.id==='pageSearch'){const start=el.selectionStart;view.query=el.value;view.tablePages={};render();const input=document.querySelector('#pageSearch');input?.focus();input?.setSelectionRange(start,start);return;}if(view.modal&&el.closest('#dialogForm'))view.modal.data=collectForm();});
root.addEventListener('submit',event=>event.preventDefault());
document.addEventListener('keydown',event=>{if(!view.modal)return;if(event.key==='Escape'){closeModal();return;}if(event.key==='Tab'){const focusable=[...document.querySelectorAll('.dialog button:not([disabled]),.dialog input,.dialog select,.dialog textarea')].filter(el=>el.offsetParent!==null);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement.classList.contains('dialog'))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement.classList.contains('dialog'))){event.preventDefault();first?.focus();}}});
render();
