import {DEMO_DATE} from './data.js';
import {companyOf,productOf,seats,serviceStatus,daysUntil} from './model.js';
import {esc,status,btn,link} from './ui.js';

// Planning fixtures only: no live telemetry, invoices or customer quota accounting.
const operationFixtures=[
  {id:'copy',product:'e2b',name:'AI 商品文案生成',companies:['c1','c3','c4'],jobs:4200,failed:42,cost:840,seconds:8,queue:2,running:4,retries:28,retryCost:12,resource:'輸入 8.4M / 輸出 2.1M Token',provider:'文字模型 A',issue:'供應商限流'},
  {id:'image',product:'e2b',name:'AI 商品圖片生成',companies:['c1','c4'],jobs:860,failed:43,cost:2580,seconds:42,queue:0,running:0,retries:38,retryCost:114,resource:'860 張圖片',provider:'圖片模型 B',issue:'生成逾時'},
  {id:'video',product:'e2b',name:'社群影音分析',companies:['c1','c4'],jobs:320,failed:24,cost:3840,seconds:186,queue:12,running:3,retries:19,retryCost:228,resource:'960 分鐘影音',provider:'多模態模型 C',issue:'解析或處理逾時'},
  {id:'analysis',product:'e2b',name:'商品分析',companies:['c1','c3','c4'],jobs:1800,failed:9,cost:540,seconds:15,queue:1,running:2,retries:7,retryCost:3,resource:'3.6M Token',provider:'分析模型 A',issue:'資料格式錯誤'},
  {id:'publish',product:'web',name:'網站發布',companies:['c1','c2','c5','c7','c8'],jobs:280,failed:4,cost:140,seconds:12,queue:1,running:1,retries:3,retryCost:2,resource:'14 GB 傳輸',provider:'發布與 CDN',issue:'資產驗證失敗'},
  {id:'forms',product:'web',name:'表單送出',companies:['c2','c7','c8'],jobs:1560,failed:3,cost:78,seconds:1,queue:0,running:0,retries:2,retryCost:1,resource:'1,560 次請求',provider:'表單與郵件',issue:'郵件暫時失敗'}
];
const dashFmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:1});
const dashMoney=n=>'NT$ '+dashFmt(n);
const dashSelected=(v,p)=>!v.dashProduct||v.dashProduct==='all'||v.dashProduct===p;
const dashTotal=(rows,key)=>rows.reduce((n,r)=>n+r[key],0);
const dashUnique=values=>new Set(values).size;
function dashPanel(title,sub,body,tools=''){return `<section class="dash-panel"><header><div><h2>${title}</h2><p>${sub}</p></div>${tools}</header>${body}</section>`;}
function dashControl(label,key,value,active){return `<button class="btn small ${active?'selected':'ghost'}" data-action="dashSet" data-key="${key}" data-value="${value}" aria-pressed="${active}">${label}</button>`;}
function dashTable(head,rows){return `<div class="table-scroll"><table class="dash-table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${head.length}">目前沒有符合條件的資料</td></tr>`}</tbody></table></div>`;}
function dashStats(items){return `<div class="dash-kpis">${items.map(([label,value,unit,note])=>`<div class="dash-kpi"><div><span>${label}</span></div><strong>${value}<small>${unit}</small></strong><p>${note}</p></div>`).join('')}</div>`;}
export function dashboardOperations(v){
  const period=[7,30,90].includes(Number(v.dashPeriod))?Number(v.dashPeriod):30;
  return operationFixtures.filter(r=>dashSelected(v,r.product)).map(r=>({...r,jobs:Math.round(r.jobs*period/30),failed:Math.round(r.failed*period/30),cost:Math.round(r.cost*period/30),retries:Math.round(r.retries*period/30),retryCost:Math.round(r.retryCost*period/30),period}));
}
export function dashboardCustomers(s,v){
  const es=s.entitlements.filter(e=>dashSelected(v,e.product));
  const active=es.filter(e=>['使用中','即將到期'].includes(serviceStatus(s,e).label));
  const ids=v.dashProduct&&v.dashProduct!=='all'?new Set(es.map(e=>e.company)):new Set(s.companies.map(c=>c.id));
  return {es,active,companies:s.companies.filter(c=>ids.has(c.id)),effective:dashUnique(active.map(e=>e.company)),due:active.filter(e=>serviceStatus(s,e).label==='即將到期'),waiting:es.filter(e=>e.stage==='等待開通')};
}
function operationsTrend(rows,metric){
  const sum=dashTotal(rows,metric==='cost'?'cost':'jobs');
  const points=[.10,.12,.13,.15,.14,.17,.19].map(x=>Math.floor(sum*x));points[6]+=sum-points.reduce((a,b)=>a+b,0);
  const max=Math.max(...points,1);const color=metric==='cost'?'#9a7741':'#277f81';
  return `<div class="ops-trend-summary"><strong>${metric==='cost'?dashMoney(sum):dashFmt(sum)+' 件'}</strong><span>所選期間合計 · ${metric==='cost'?'含失敗與重試的估計成本':'已完成＋失敗，不含目前排隊與執行中'}</span></div><div class="chart-container"><svg viewBox="0 0 660 220" role="img" aria-label="${metric==='cost'?'估計成本':'已結束任務'}趨勢；所選期間分成七個等長區段">${[0,1,2,3].map(i=>`<line class="chart-grid" x1="45" x2="640" y1="${175-i*48}" y2="${175-i*48}"/><text x="37" y="${179-i*48}" text-anchor="end">${dashFmt(Math.round(max*i/3))}</text>`).join('')}${points.map((n,i)=>`<rect x="${65+i*82}" y="${175-n/max*144}" width="42" height="${n/max*144}" rx="4" fill="${color}" opacity="${.45+i*.08}"><title>第 ${i+1} 區段：${dashFmt(n)} ${metric==='cost'?'元':'件'}</title></rect><text x="${86+i*82}" y="202" text-anchor="middle">區段 ${i+1}</text>`).join('')}</svg></div><p class="chart-footnote">模擬趨勢，非監控實測。七個等長區段合計與摘要一致。</p>`;
}
function featureRanking(s,v,rows){
  const rank=v.dashRank||'cost';const sorted=[...rows].sort((a,b)=>rank==='companies'?b.companies.length-a.companies.length:rank==='jobs'?b.jobs-a.jobs:b.cost-a.cost);
  const value=r=>rank==='companies'?r.companies.length:r[rank];const max=Math.max(...sorted.map(value),1);
  const body=sorted.map((r,i)=>`<button class="ops-rank-row ${v.dashFeature===r.id?'active':''}" data-action="dashSet" data-key="dashFeature" data-value="${r.id}" aria-expanded="${v.dashFeature===r.id}"><span class="ops-rank-no">0${i+1}</span><span class="ops-rank-name"><b>${r.name}</b><small>${productOf(s,r.product).name} · ${r.companies.length} 間曾使用</small></span><span class="horizontal-track teal"><i style="width:${value(r)/max*100}%"></i></span><strong>${rank==='cost'?dashMoney(r.cost):dashFmt(value(r))+(rank==='companies'?' 間':' 件')}</strong><span>↗</span></button>`).join('');
  return dashPanel('哪些功能最值得關注？','使用廣度、處理量與成本分開比較；點選功能查看明細。',body,`<div class="segmented">${dashControl('使用公司','dashRank','companies',rank==='companies')}${dashControl('任務量','dashRank','jobs',rank==='jobs')}${dashControl('消耗成本','dashRank','cost',rank==='cost')}</div>`);
}
function featureDrill(s,v,rows){
  const r=rows.find(r=>r.id===v.dashFeature);if(!r)return '';
  const done=r.jobs-r.failed;
  return `<div id="dashboard-feature-detail">${dashPanel(`${r.name} · 使用與消耗明細`,'此區為規劃展示；歷史使用公司可能包含目前已到期客戶。',`<div class="ops-detail-strip"><div><small>成功／失敗</small><b>${dashFmt(done)} / ${dashFmt(r.failed)} 件</b></div><div><small>每件成功任務成本</small><b>${dashMoney(done?r.cost/done:0)}</b></div><div><small>重試／重試成本（已含於總成本）</small><b>${dashFmt(r.retries)} 次 / ${dashMoney(r.retryCost)}</b></div><div><small>原始資源 · 固定近 30 天範例</small><b>${r.resource}</b></div></div><div class="ops-detail-copy"><p>${r.provider} · 平均完成 ${r.seconds} 秒 · 失敗原因範例：${r.issue}</p><p>期間使用公司：${r.companies.map(id=>link(companyOf(s,id).short,'company',`data-id="${id}" data-product="${r.product}"`)).join('、')}</p><p>結果品質：尚未接入採用率或人工評分，不能由技術成功率推論內容品質。</p></div>`,dashControl('收起','dashFeature','',false))}</div>`;
}
function productDashboard(s,v){
  const rows=dashboardOperations(v),jobs=dashTotal(rows,'jobs'),failed=dashTotal(rows,'failed'),cost=dashTotal(rows,'cost');
  const ai=rows.filter(r=>r.product==='e2b'),aiJobs=dashTotal(ai,'jobs');const metric=v.dashMetric==='cost'?'cost':'jobs';
  const products=s.products.filter(p=>dashSelected(v,p.id));
  const health=products.map(p=>{const degraded=p.id==='e2b';const features=s.features.filter(f=>f.product===p.id);return `<div class="ops-service"><div><span class="ops-service-dot ${degraded?'warn':''}"></span><b>${p.name}</b>${status(!p.enabled?'全域停用':degraded?'部分服務降級':'服務正常',!p.enabled?'bad':degraded?'warn':'ok')}</div><p>${degraded?'影音分析等待偏長；生成服務依賴需關注':'網站瀏覽、發布與表單服務正常'}</p><div class="ops-service-values"><span>模擬可用率 <b>${degraded?'99.92':'99.98'}%</b></span><span>API P95 <b>${degraded?'820':'240'} ms</b></span><span>目前開啟功能 <b>${features.filter(f=>f.enabled).length}/${features.length}</b></span></div>${link('產品與功能 →','product',`data-id="${p.id}"`)}</div>`;}).join('');
  const events=products.map(p=>p.id==='e2b'?`<div class="ops-event"><span class="priority high">需關注</span><div><b>影音分析處理延遲</b><p>快照 14:20 · 12 件等待 · 影響遠星科技、星河教育</p></div>${dashControl('查看分析','dashFeature','video',v.dashFeature==='video')}</div>`:`<div class="ops-event"><span class="priority">追蹤</span><div><b>網站發布曾發生資產驗證失敗</b><p>所選期間 ${rows.find(r=>r.id==='publish')?.failed||0} 件 · 目前發布服務正常</p></div>${dashControl('查看發布','dashFeature','publish',v.dashFeature==='publish')}</div>`).join('');
  const pipeline=ai.length?dashPanel('AI 任務處理','期間結果與目前快照分開呈現。',`<div class="ops-pipeline">${[['成功',aiJobs-dashTotal(ai,'failed')],['失敗',dashTotal(ai,'failed')],['執行中',dashTotal(ai,'running')],['排隊中',dashTotal(ai,'queue')]].map(([l,n])=>`<div><span>${l}</span><strong>${dashFmt(n)}</strong><small>${['成功','失敗'].includes(l)?'所選期間 · 件':'目前快照 · 件'}</small></div>`).join('')}</div><div class="ops-detail-copy"><p>最久等待 <b>8 分 20 秒</b> · 慢速任務 P95 <b>246 秒</b>（模擬快照）</p><p>重試 ${dashFmt(dashTotal(ai,'retries'))} 次，已計入成本；不重複算成新任務。</p></div>`):dashPanel('官網服務觀察','網站瀏覽與客戶後台操作分開統計。',`<div class="ops-pipeline"><div><span>公開網站</span><strong>${s.websites.length}</strong><small>已建置站點；不以合約推論下線</small></div><div><span>憑證異常</span><strong>0</strong><small>目前模擬快照</small></div></div><div class="ops-detail-copy"><p>頁面載入 P95：1.8 秒 · 備份最近成功：02:00（展示）</p><p>網站訪客流量尚未接入，不與後台任務數混算。</p></div>`);
  const costRows=rows.map(r=>`<tr><td>${r.name}</td><td>${dashMoney(r.cost)}</td><td>${dashMoney(r.jobs>r.failed?r.cost/(r.jobs-r.failed):0)}</td><td>${dashMoney(r.retryCost)}</td></tr>`).join('');
  return `<div class="ops-section-heading"><div><span class="ops-eyebrow">PRODUCT OPERATIONS</span><h2>掌握服務健康，也看見資源去向。</h2></div><span>模擬快照 14:20 · 非即時監控</span></div>${dashStats([['已結束任務',dashFmt(jobs),'件','所選期間 · 成功與失敗合計'],['任務成功率',jobs?((jobs-failed)/jobs*100).toFixed(1):'—','%',`${dashFmt(failed)} 件失敗 · 不代表結果品質`],['估計資源成本',dashMoney(cost),'','所選期間 · 包含失敗與重試'],['目前排隊',dashFmt(dashTotal(rows,'queue')),'件','快照數據 · 不隨期間累加']])}<div class="dash-row-grid">${dashPanel('服務健康','可用率與延遲為模擬；功能開關依目前展示設定。',health)}${pipeline}</div>${dashPanel('需要關注的事件','異常 → 功能 → 受影響客戶',events)}<div class="dash-row-grid ops-spaced">${dashPanel(metric==='cost'?'資源成本趨勢':'任務處理趨勢','依所選產品與期間切換',operationsTrend(rows,metric),`<div class="segmented">${dashControl('任務量','dashMetric','jobs',metric==='jobs')}${dashControl('成本','dashMetric','cost',metric==='cost')}</div>`)}${dashPanel('資源效率','NT$ 估算展示，不代表實際帳單或客戶額度扣點。',dashTable(['功能','總成本','每成功件','重試成本'],costRows))}</div>${featureRanking(s,v,rows)}<div class="ops-spaced">${featureDrill(s,v,rows)}</div>${releasePanel(s,v)}`;
}
function releasePanel(s,v){const rows=s.releases.filter(r=>dashSelected(v,r.product)).slice(0,3).map(r=>`<tr><td>${link(r.name,'release',`data-id="${r.id}"`)}</td><td>${productOf(s,r.product).name}</td><td>${esc(r.version)}</td><td>${status(r.status)}</td><td>${esc(r.time)}</td></tr>`).join('');return dashPanel('最近發布與變更','目前最新紀錄 · 可用來對照異常發生時間',dashTable(['發布項目','產品','版本','狀態','時間'],rows),link('所有發布 →','releases'));}
function customerDashboard(s,v){
  const {es,active,companies,effective,due,waiting}=dashboardCustomers(s,v);
  const qs=s.quotas.filter(q=>dashSelected(v,q.product));
  const combo=[0,0,0,0];companies.forEach(c=>{const ps=new Set(active.filter(e=>e.company===c.id).map(e=>e.product));combo[ps.has('e2b')&&ps.has('web')?2:ps.has('e2b')?0:ps.has('web')?1:3]++;});
  const labels=['僅 E2B 有效','僅官網有效','兩個產品皆有效','目前無有效產品'];const colors=['#327ac1','#238f88','#9a85b7','#c0c9d1'];
  const composition=`<div class="ops-composition">${combo.map((n,i)=>`<span style="width:${companies.length?n/companies.length*100:0}%;background:${colors[i]}" title="${labels[i]} ${n} 間"></span>`).join('')}</div><div class="ops-combo-list">${labels.map((l,i)=>`<div><i style="background:${colors[i]}"></i><span>${l}</span><b>${combo[i]} 間</b></div>`).join('')}</div><p class="chart-footnote">依所選產品的目前有效服務分類，每家公司只計一次；無有效產品不等於公司停用。</p>`;
  const productRows=s.products.filter(p=>dashSelected(v,p.id)).map(p=>{const pe=es.filter(e=>e.product===p.id);return `<tr><td>${link(p.name,'product',`data-id="${p.id}"`)}</td><td>${dashUnique(active.filter(e=>e.product===p.id).map(e=>e.company))}</td><td>${due.filter(e=>e.product===p.id).length}</td><td>${pe.filter(e=>serviceStatus(s,e).label==='已到期').length}</td><td>${pe.filter(e=>serviceStatus(s,e).label.includes('暫停')||serviceStatus(s,e).label==='產品全域停用').length}</td><td>${pe.filter(e=>['等待開通','尚未開始'].includes(serviceStatus(s,e).label)).length}</td></tr>`;}).join('');
  const attention=es.map(e=>({e,st:serviceStatus(s,e),n:seats(s,e)})).filter(({st,n})=>st.label!=='使用中'||n.used>=n.limit);
  const attentionRows=attention.map(({e,st,n})=>`<tr><td>${link(companyOf(s,e.company).short,'company',`data-id="${e.company}" data-product="${e.product}"`)}</td><td>${productOf(s,e.product).name}</td><td>${status(st.label,st.tone)}${n.used>=n.limit?'<small>帳號名額已滿</small>':''}</td><td>${e.end}<small>${daysUntil(e.end)<0?'已超過到期日':`剩餘 ${daysUntil(e.end)} 天`}</small></td><td>${n.used} / ${n.limit}</td><td>${link('查看公司 →','company',`data-id="${e.company}" data-product="${e.product}"`)}</td></tr>`).join('');
  const quotaRows=[...qs].sort((a,b)=>b.used/b.total-a.used/a.total).map(q=>`<button class="quota-chart-row" data-action="quotaEdit" data-id="${q.id}"><div><b>${companyOf(s,q.company).short}</b><small>${q.name} · ${q.used}/${q.total} ${q.unit}</small></div><div class="horizontal-track ${q.used/q.total>=.85?'amber':'teal'}"><i style="width:${Math.min(100,q.used/q.total*100)}%"></i></div><strong>${Math.round(q.used/q.total*100)}%</strong></button>`).join('');
  const tasks=s.tasks.filter(t=>t.state!=='已處理'&&dashSelected(v,t.product));
  const taskRows=tasks.slice(0,5).map(t=>`<div class="dash-task"><span class="priority ${t.priority==='高'?'high':''}">${esc(t.priority)}</span><div><b>${esc(t.title)}</b><p>${esc(t.desc)}</p></div>${btn('處理','task',`data-id="${t.id}"`,'small ghost')}</div>`).join('');
  return `<div class="ops-section-heading"><div><span class="ops-eyebrow">CUSTOMER OPERATIONS</span><h2>哪些客戶正在使用，哪些需要協助？</h2></div><span>目前狀態 · 同公司去重計算</span></div>${dashStats([['客戶公司',companies.length,'間','目前所選產品關聯公司'],['有效服務公司',effective,'間','至少一項所選產品有效；含即將到期'],['30 天內到期',dashUnique(due.map(e=>e.company)),'間',`${due.length} 項有效產品服務即將到期`],['等待開通',dashUnique(waiting.map(e=>e.company)),'間',`${waiting.length} 項已申請服務；不含未購買產品`]])}<div class="dash-chart-grid">${dashPanel('各產品的客戶服務狀態','有效含即將到期；同公司可分別使用兩個產品，跨產品不可直接加總。',dashTable(['產品','有效公司','其中快到期','已到期','暫停／停用','待開通／開始'],productRows),link('客戶公司 →','companies',`data-product-filter="${v.dashProduct||'all'}"`))}${dashPanel('客戶的產品組合','目前有效服務 · 公司數',composition)}</div>${dashPanel('優先關注的客戶','到期、停用、等待開通或名額已滿；點入公司可繼續處理。',dashTable(['公司','產品','狀態／提醒','到期日','已占名額',''],attentionRows))}<div class="dash-row-grid ops-spaced">${dashPanel('客戶額度使用','目前配額週期 · 客戶額度不等於內部資源成本。',quotaRows||'<p class="dash-empty">尚無配額資料</p>',link('用量明細 →','quotas'))}${dashPanel('待處理事項',`${tasks.length} 件未處理 · 依所選產品篩選`,taskRows||'<p class="dash-empty">沒有待處理事項</p>',link('全部事項 →','tasks'))}</div>`;
}
export function dashboard(s,v){
  const mode=v.dashMode||'product',product=v.dashProduct||'all';
  return `<div class="dashboard operations-dashboard"><div class="ops-toolbar"><div class="ops-view-switch" role="group" aria-label="Dashboard視角">${dashControl('產品總覽','dashMode','product',mode==='product')}${dashControl('客戶總覽','dashMode','customer',mode==='customer')}</div><div class="dashboard-context"><div><select aria-label="Dashboard產品" data-view="dashProduct"><option value="all" ${product==='all'?'selected':''}>全部產品</option>${s.products.map(p=>`<option value="${p.id}" ${product===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>${mode==='product'?`<select aria-label="Dashboard期間" data-view="dashPeriod">${[7,30,90].map(n=>`<option value="${n}" ${Number(v.dashPeriod||30)===n?'selected':''}>近 ${n} 天</option>`).join('')}</select>`:'<span>目前快照</span>'}</div></div></div><div class="ops-demo-note"><b>規劃展示</b><span>客戶狀態基準 ${DEMO_DATE}；雲端健康、AI 任務、使用量與成本為獨立模擬情境，尚未串接監控或帳務。</span></div>${mode==='product'?productDashboard(s,v):customerDashboard(s,v)}<details class="ops-definitions"><summary>指標口徑與待確認事項</summary><p>期間僅影響產品總覽的任務、成本與排行；排隊、服務健康、發布紀錄與客戶狀態都是快照。近 7／30／90 天數據為等比例規劃範例，非真實歷史。</p><p>使用公司數按公司去重；有效服務不代表近期活躍。AI 成功率＝成功件數÷已結束任務數；重試不另算新任務。成本包含失敗與重試，與客戶方案扣點分開。</p><p>可用率與告警門檻、AI 成本單價、品質評分、活躍定義、預算以及公開網站到期政策，均待後續確認。原始資源明細目前固定展示近 30 天範例。</p></details></div>`;
}
